import { CollectionLinks } from './CollectionPage'
import { useState } from 'react'
import { ArrowUpRight, RotateCcw, Search, SlidersHorizontal, X } from 'lucide-react'
import { bags, tx, type Bag, type Lang } from './data'
import { materialCategories, styleOptions, usageOptions } from './catalog-data'
import { href } from './routes'
import { ProductCard } from './Catalog'

const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const family=(b:Bag)=>!b.collection?'extended':b.type==='ice'?'ice':b.type==='foil'?'foil':b.category==='non-woven'?'takeaway':'coolers'
export default function CatalogBrowser({lang}:{lang:Lang}) {
  const [range,setRange]=useState('all'), [material,setMaterial]=useState('all'), [style,setStyle]=useState('all'), [usage,setUsage]=useState('all'), [query,setQuery]=useState(''), [showFilters,setShowFilters]=useState(false)
  const t=(en:string,zh:string,es:string)=>tx(en,zh,es)[lang]
  const ranges=[['all',t('All products','全部产品','Todos')],['foil',t('Foil bags','铝箔保温袋','Bolsas de aluminio')],['takeaway',t('Takeaway totes','外卖手提袋','Bolsas para comida')],['coolers',t('Cooler bags','保温包','Bolsas isotérmicas')],['ice',t('Ice packs','冰袋与冰格','Acumuladores de frío')],]
  const clearDetails=()=>{setMaterial('all');setStyle('all');setUsage('all');setQuery('')}
  const reset=()=>{setRange('all');clearDetails()}
  const filtered=bags.filter(b=>(range==='all'||family(b)===range)&&(material==='all'||b.category===material)&&(style==='all'||b.styles?.includes(style))&&(usage==='all'||b.uses?.includes(usage))&&normalize([b.name.en,b.name.zh,b.name.es,b.material[lang],b.use[lang],...styleOptions.filter(([id])=>b.styles?.includes(id)).map(([,v])=>v[lang]),...usageOptions.filter(([id])=>b.uses?.includes(id)).map(([,v])=>v[lang])].join(' ')).includes(normalize(query.trim())))
  const active=range!=='all'||material!=='all'||style!=='all'||usage!=='all'||query!==''
  const detailCount=[material,style,usage].filter(v=>v!=='all').length
  const own=filtered.filter(b=>b.collection), extended=filtered.filter(b=>!b.collection)
  const grid=(items:Bag[])=><div className="product-grid">{items.map(b=><ProductCard key={b.slug} bag={b} lang={lang} index={bags.indexOf(b)}/>)}</div>
  return <section className="container page-section product-catalog">
    <nav className="breadcrumbs" aria-label={t('Breadcrumb','面包屑导航','Ruta de navegación')}><a href={href('/',lang)}>{t('Home','首页','Inicio')}</a><span>/</span><span aria-current="page">{t('Products','产品中心','Productos')}</span></nav>
    <div className="catalog-heading"><div><span className="eyebrow">{t('THE PRODUCT COLLECTION','远恩产品系列','COLECCIÓN DE PRODUCTOS')}</span><h1>{t('Insulated Bags & Cold-Chain Packaging','保温袋与冷链包装产品','Bolsas térmicas y embalaje de cadena de frío')}</h1><p>{t('Explore insulated bags, takeaway totes and cold-chain packaging. Start with a format, then make the material, size and print your own.','从铝箔保温袋、外卖手提袋到配套冰袋。先选袋型，再按您的品牌定制材质、尺寸与印刷。','Explore bolsas térmicas, bolsas para comida y embalajes de frío. Elija el formato y personalice material, medidas e impresión.')}</p></div><a className="text-link" href={href('/contact/',lang)}>{t('Need help choosing?','需要选型建议？','¿Necesita ayuda para elegir?')}<ArrowUpRight size={18}/></a></div>
    <CollectionLinks lang={lang}/><div className="catalog-controls"><div className="range-tabs" aria-label={t('Product ranges','产品系列','Gamas de productos')}>{ranges.map(([id,label])=><button key={id} aria-pressed={range===id} onClick={()=>{clearDetails();setRange(id)}}>{label}<span>{id==='all'?bags.length:bags.filter(b=>family(b)===id).length}</span></button>)}</div>
    <div className="catalog-searchbar"><label className="product-search"><Search size={19}/><input aria-label={t('Search products','搜索产品','Buscar productos')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search a product, material or use…','搜索产品、材质或用途…','Buscar producto, material o uso…')}/>{query&&<button type="button" className="icon-button" aria-label={t('Clear search','清空搜索','Borrar búsqueda')} onClick={()=>setQuery('')}><X size={17}/></button>}</label><button className="filter-toggle" aria-expanded={showFilters} aria-controls="advanced-product-filters" onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={17}/>{t('Filter','筛选','Filtrar')}{detailCount>0&&<span>{detailCount}</span>}</button></div>
    <div id="advanced-product-filters" className="advanced-filters" hidden={!showFilters}><label>{t('Material','材质','Material')}<select value={material} onChange={e=>setMaterial(e.target.value)}><option value="all">{t('All materials','全部材质','Todos los materiales')}</option>{materialCategories.filter(([id])=>bags.some(b=>b.category===id)).map(([id,label])=><option key={id} value={id}>{label[lang]}</option>)}</select></label><label>{t('Bag style','袋型方向','Formato de bolsa')}<select value={style} onChange={e=>setStyle(e.target.value)}><option value="all">{t('All formats','全部袋型','Todos los formatos')}</option>{styleOptions.filter(([id])=>bags.some(b=>b.styles?.includes(id))).map(([id,label])=><option key={id} value={id}>{label[lang]}</option>)}</select></label><label>{t('Application','应用场景','Aplicación')}<select value={usage} onChange={e=>setUsage(e.target.value)}><option value="all">{t('All applications','全部用途','Todas las aplicaciones')}</option>{usageOptions.filter(([id])=>bags.some(b=>b.uses?.includes(id))).map(([id,label])=><option key={id} value={id}>{label[lang]}</option>)}</select></label></div></div>
    <div className="results-bar"><p role="status" aria-live="polite">{filtered.length} {t('products & ranges','个产品与系列','productos y gamas')}</p>{active&&<button className="reset-filters" onClick={reset}><RotateCcw size={14}/>{t('Reset filters','重置筛选','Restablecer filtros')}</button>}</div>
    {own.length>0&&<section className="catalog-group"><div className="catalog-group-title"><h2>{t('Insulated packaging collection','保温包装系列','Colección de embalajes térmicos')}</h2><span>YUANEN / 2026</span></div>{grid(own)}</section>}
    {extended.length>0&&<section className="catalog-group extended-group"><div className="catalog-group-title"><h2>{t('Materials & custom formats','材质与定制袋型','Materiales y formatos a medida')}</h2><a className="text-link" href={href('/guides/bag-material-comparison/',lang)}>{t('Compare materials','选材指南','Comparar materiales')}<ArrowUpRight size={16}/></a></div><p className="range-explanation">{t('Explore additional development directions. Reference designs and format illustrations are identified on each product.','更多选材与开发方向，参考款与袋型示意已分别标注。','Explore más opciones de desarrollo. Las referencias e ilustraciones están identificadas en cada producto.')}</p>{grid(extended)}</section>}
    {!filtered.length&&<div className="empty-state"><Search size={32}/><h2>{t('No matching products','没有匹配的产品','No hay productos coincidentes')}</h2><p>{t('Try another keyword or reset your filters.','换一个关键词，或重置筛选条件。','Pruebe otra palabra o restablezca los filtros.')}</p><button className="button outline" onClick={reset}>{t('Reset filters','重置筛选','Restablecer filtros')}</button></div>}
    <div className="catalog-help"><div><span className="eyebrow">{t('YOUR NEXT PACKAGING PROJECT','开始您的包装项目','SU PRÓXIMO PROYECTO')}</span><h2>{t('A different size, print or construction?','尺寸、印花、结构，都可以沟通。','¿Otra medida, impresión o estructura?')}</h2><p>{t('Share the contents, quantity and destination. We will help define the right specification.','告诉我们内装物、采购数量与目的地，一起明确合适的产品方案。','Comparta contenido, cantidad y destino para definir la especificación adecuada.')}</p></div><a className="button primary" href={href('/contact/',lang)}>{t('Start an enquiry','提交定制需求','Preparar consulta')}<ArrowUpRight size={18}/></a></div>
  </section>
}
