import type { Bag, Text } from './data'

const t = (en:string, zh:string, es:string):Text => ({en,zh,es})
export const materialCategories = [
  ['non-woven',t('Non-woven','无纺布','Tejido no tejido')],
  ['cooler',t('Insulation & cold chain','保温与冷链','Aislamiento y cadena de frío')],
  ['pp-woven',t('PP woven','PP 编织','PP tejido')],
  ['rpet-non-woven',t('RPET non-woven','RPET 无纺布','RPET no tejido')],
  ['rpet-polyester',t('RPET polyester','RPET 涤纶','Poliéster RPET')],
  ['polyester',t('Polyester','涤纶','Poliéster')],
  ['cotton-canvas',t('Cotton & canvas','棉布 / 帆布','Algodón y lona')],
  ['reflective',t('Reflective fabric','反光面料','Tejido reflectante')],
  ['felt',t('Felt','毛毡','Fieltro')],
  ['paper',t('Paper & washable paper','纸 / 水洗纸','Papel y papel lavable')],
  ['glitter',t('Glitter & metallic','闪光 / 金属效果','Purpurina y metalizados')],
  ['tyvek',t('Tyvek','Tyvek 材料','Tyvek')],
  ['pvc-tpu',t('PVC & TPU','PVC / TPU','PVC y TPU')],
  ['mesh',t('Cotton & polyester mesh','棉 / 涤纶网布','Malla de algodón y poliéster')],
  ['jute',t('Jute','黄麻','Yute')],
  ['bamboo',t('Bamboo-derived fiber','竹来源纤维','Fibra derivada de bambú')],
  ['leather',t('Leather & alternatives','皮革及替代材料','Cuero y alternativas')],
  ['other',t('Other custom materials','其他材质定制','Otros materiales a medida')],
] as const
export const styleOptions = [
  ['handle',t('Handle / tote','手提袋','Bolsa con asas')],['postman',t('Shoulder / messenger','邮差 / 单肩袋','Bandolera')],['foldable',t('Foldable','折叠袋','Plegable')],['drawstring',t('Drawstring / backpack','抽绳 / 背包','Cordón / mochila')],['beach',t('Beach bag','沙滩袋','Bolsa de playa')],['bowling',t('Bowling / duffel','保龄球 / 旅行袋','Bolsa de viaje')],['garment',t('Garment bag','服装袋','Portatrajes')],['zipper',t('Zipper bag','拉链袋','Bolsa con cremallera')],['round',t('Rounded corners','圆角袋','Esquinas redondeadas')],['ultrasonic',t('Ultrasonic bonded','超声波热合袋','Sellado ultrasónico')],['basket',t('Basket bag','篮式袋','Bolsa cesta')],['other',t('Other formats','其他袋型','Otros formatos')],
] as const
export const usageOptions = [
  ['shopping',t('Shopping','购物','Compras')],['shoe',t('Shoe packaging','鞋袋','Calzado')],['promotion',t('Promotional & gifts','促销 / 礼赠','Promoción y regalos')],['thermal',t('Thermal / cooler','保温 / 保冷','Aislamiento térmico')],['beach-mat',t('Beach mat','沙滩垫','Esterilla de playa')],['storage',t('Storage box','收纳箱','Caja de almacenaje')],['supermarket',t('Supermarket','商超','Supermercado')],['cosmetic',t('Cosmetics','化妆收纳','Cosméticos')],['garbage',t('Waste collection','垃圾收集','Recogida de residuos')],['suit',t('Suit cover','西装防尘罩','Funda para trajes')],['reflective',t('Reflective accessories','反光配件','Accesorios reflectantes')],['bicycle',t('Bicycle accessories','自行车配件','Accesorios de bicicleta')],['wine',t('Wine bottle packaging','酒瓶包装','Botellas de vino')],['computer',t('Laptop / tablet sleeve','电脑 / 平板套','Funda de portátil / tableta')],['glasses',t('Glasses pouch','眼镜袋','Funda de gafas')],['other',t('Other applications','其他用途','Otras aplicaciones')],
] as const

// These are development/selection directions, not validated performance claims.
export const catalogDetails:Record<string,Partial<Bag>> = {
  'zipper-insulated-bags':{category:'cooler',styles:['handle','zipper','basket'],uses:['thermal','supermarket','shopping'],image:'zipper-insulated-bags.webp',source:'non-woven-cooler-bag-with-bottom-but-no-gusset.html'},
  'hook-loop-insulated-bags':{category:'cooler',styles:['handle','other'],uses:['thermal','supermarket']},
  'non-woven-bags':{category:'non-woven',styles:['handle','foldable','ultrasonic','drawstring','garment'],uses:['shopping','promotion','supermarket','shoe','suit'],image:'non-woven-bags.webp',source:'non-woven-bag-111.html'},
  'foil-insulated-bags':{category:'cooler',styles:['handle','zipper'],uses:['thermal','supermarket']},
  'epe-foam-insulated-bags':{category:'cooler',styles:['other'],uses:['thermal']},
  'ice-packs':{category:'cooler',styles:['other'],uses:['thermal']},
}

type Entry = {slug:string;category:string;name:Text;intro:Text;material:Text;use:Text;styles:string[];uses:string[];points:Text[];q:Text;a:Text;source?:string}
const entries:Entry[] = [
  {
    slug:'pp-woven-bags',category:'pp-woven',name:t('Custom PP woven bags','定制 PP 编织袋','Bolsas de PP tejido personalizadas'),
    intro:t('PP woven shopping bags use interlaced polypropylene tapes. Compare laminated graphics, base reinforcement and handle attachment for supermarket, retail and repeat-use carrying projects.','PP 编织购物袋采用聚丙烯扁丝交织结构。用于商超、零售及重复提携项目时，应一起比较覆膜印刷、底部加固和提手连接方式。','Las bolsas de PP tejido utilizan cintas de polipropileno entrelazadas. Compare el laminado, el refuerzo de la base y la fijación de las asas para proyectos de comercio y supermercado.'),
    material:t('Woven polypropylene; optional laminated finish','聚丙烯编织布；覆膜方案待选','Polipropileno tejido; laminado según proyecto'),use:t('Supermarket · Shopping · Storage','商超 · 购物 · 收纳','Supermercado · Compras · Almacenaje'),styles:['handle','zipper','basket','foldable'],uses:['shopping','supermarket','storage','beach-mat','garbage'],
    points:[t('Specify base fabric GSM separately from the finished laminated weight. Include the film and print coverage in the quotation.','区分基布克重与覆膜后总克重，报价应包含膜层与印刷覆盖范围。','Separe el gramaje del tejido del peso final laminado; incluya película e impresión en la cotización.'),t('Define the filled load, handle length and reinforcement. Test the finished bag at the intended load.','明确装载重量、提手长度及加固位置，按预期负载测试成品。','Defina carga, longitud de asas y refuerzos; ensaye la bolsa terminada con la carga prevista.'),t('Review fold lines, print registration and seam positions on a full-size sample.','用足尺样品核对折线、印刷套色与接缝位置。','Revise pliegues, registro de impresión y costuras en una muestra a tamaño real.')],
    q:t('How is PP woven different from PP non-woven?','PP 编织布与 PP 无纺布有什么区别？','¿En qué se diferencian el PP tejido y el no tejido?'),a:t('Woven PP is made from interlaced tapes; non-woven PP uses bonded fibers. Construction, coating, seams and handles affect the finished bag. A material name alone does not establish load capacity or reusability.','PP 编织布由扁丝交织形成，PP 无纺布由纤维固结形成。成品表现还取决于涂层、接缝与提手，不能仅按材料名称判断承重或可重复使用次数。','El PP tejido entrelaza cintas; el no tejido une fibras. Revestimientos, costuras y asas también influyen. El nombre del material no determina por sí solo la carga admisible ni los ciclos de uso.'),source:'transparent-pp-woven-shopping-bag.html',
  },
  {
    slug:'rpet-non-woven-bags',category:'rpet-non-woven',name:t('Custom RPET non-woven bags','定制 RPET 无纺布袋','Bolsas de RPET no tejido personalizadas'),
    intro:t('RPET non-woven bags are a material option for branded shopping and gift packaging. Specify the recycled PET content, fabric weight and construction, with traceability documents matched to the order.','RPET 无纺布袋可作为品牌购物及礼品包装的选材方向。需确认再生 PET 比例、面料克重与成型结构，并核对与订单对应的追溯文件。','Las bolsas de RPET no tejido son una opción para compras y regalos de marca. Especifique contenido de PET reciclado, gramaje y confección, junto con documentos de trazabilidad del pedido.'),
    material:t('Recycled PET non-woven; recycled percentage to verify','再生 PET 无纺布；再生成分比例需核实','PET reciclado no tejido; porcentaje por verificar'),use:t('Gift packaging · Retail · Promotions','礼品包装 · 零售 · 促销','Regalos · Comercio · Promoción'),styles:['handle','drawstring','ultrasonic'],uses:['shopping','promotion','supermarket'],
    points:[t('Request fiber composition and the recycled percentage for each layer, including any lamination.','索取各层纤维成分与再生比例，覆膜层也应单独说明。','Solicite composición y porcentaje reciclado de cada capa, incluido cualquier laminado.'),t('Agree on GSM, stiffness, seam method and ribbon or webbing handles.','确认克重、挺度、接缝工艺及缎带或织带提手。','Acuerde gramaje, rigidez, costuras y asas de cinta o cincha.'),t('Match any certification claim to valid documents covering the supplier, material and transaction.','如使用认证表述，应核对覆盖供应商、材料与交易的有效文件。','Vincule toda afirmación de certificación a documentos válidos del proveedor, material y transacción.')],
    q:t('Does RPET automatically mean a certified recycled bag?','RPET 就代表产品有再生认证吗？','¿RPET significa que la bolsa está certificada?'),a:t('No. RPET describes recycled PET, not a certification status. Confirm the actual recycled percentage, the scope of supporting certificates and any transaction documents before using a certification label.','不是。RPET 表示再生 PET 材料，不等同于认证状态。使用认证标识前，应确认实际再生比例、证书范围及对应交易文件。','No. RPET describe PET reciclado, no un estado de certificación. Confirme el porcentaje real, el alcance de los certificados y los documentos de transacción antes de utilizar una etiqueta certificada.'),source:'christmas-rpet-non-woven-candy-bag-04.html',
  },
  {
    slug:'rpet-polyester-bags',category:'rpet-polyester',name:t('Custom RPET polyester bags','定制 RPET 涤纶袋','Bolsas de poliéster RPET personalizadas'),
    intro:t('RPET polyester is a woven-fabric option for foldable shopping bags, drawstring bags and travel pouches. Balance packed size, fabric construction, print coverage and recycled-content documentation.','RPET 涤纶是折叠购物袋、抽绳袋及旅行收纳袋的织物选材方向。开发时应平衡折叠体积、面料结构、印刷覆盖和再生成分文件。','El poliéster RPET es una opción de tejido para bolsas plegables, mochilas de cordón y estuches de viaje. Equilibre tamaño plegado, construcción del tejido, impresión y documentación del contenido reciclado.'),
    material:t('Woven recycled polyester; denier / thread count to specify','再生涤纶织物；纤度与织物密度待定','Poliéster reciclado tejido; denier / densidad por definir'),use:t('Foldable shopping · Travel · Promotions','折叠购物 · 旅行 · 促销','Compras plegables · Viaje · Promoción'),styles:['foldable','drawstring','handle','zipper','garment'],uses:['shopping','promotion','shoe','suit','cosmetic'],
    points:[t('Specify denier, weave and coating separately; a thread-count label alone is incomplete.','纤度、织法与涂层需分别确认，仅织物密度标识不足以描述完整规格。','Especifique denier, tejido y recubrimiento por separado; la densidad de hilos no basta.'),t('Check folding sequence, pouch size and stress at the handle seams.','核对折叠步骤、收纳袋尺寸及提手接缝受力。','Compruebe el plegado, el tamaño del estuche y el esfuerzo en las costuras de las asas.'),t('Review colourfastness and print appearance on the selected recycled fabric batch.','按所选再生面料批次核对色牢度与印刷效果。','Revise solidez del color y apariencia de la impresión en el lote seleccionado.')],
    q:t('Should I choose RPET polyester or RPET non-woven?','RPET 涤纶和 RPET 无纺布怎么选？','¿Conviene poliéster RPET o RPET no tejido?'),a:t('Start with the bag structure. Woven polyester is an option for compact folding formats; non-woven is another route for structured promotional packaging. Compare actual samples for feel, seams, folded size and documentation instead of treating them as interchangeable.','先看袋型需求。织造涤纶可用于紧凑折叠袋型，无纺布则是促销包装的另一选材路径。应通过样品比较手感、接缝、折叠体积和文件，不能将二者视为同一材料。','Empiece por la estructura. El poliéster tejido es una opción para formatos plegables compactos; el no tejido ofrece otra vía para embalaje promocional. Compare tacto, costuras, volumen plegado y documentación con muestras.'),source:'rpet-polyester-bag-04.html',
  },
  {
    slug:'polyester-bags',category:'polyester',name:t('Custom polyester bags & pouches','定制涤纶袋与收纳包','Bolsas y estuches de poliéster personalizados'),
    intro:t('Polyester fabrics support a range of pouch, drawstring, travel and garment-cover designs. Define the weave, finish, lining and closure around the items being carried and the print effect you need.','涤纶面料可用于收纳包、抽绳袋、旅行袋与服装罩等开发方向。根据内装物与印刷效果，确认织法、表面处理、内衬和封口。','Los tejidos de poliéster permiten desarrollar estuches, bolsas de cordón, viaje y fundas para prendas. Defina tejido, acabado, forro y cierre según el contenido y la impresión.'),
    material:t('Polyester fabric; lining and coatings to specify','涤纶面料；内衬与涂层需确认','Tejido de poliéster; forro y recubrimientos por definir'),use:t('Travel · Cosmetics · Garment storage','旅行 · 化妆收纳 · 服装防尘','Viaje · Cosméticos · Prendas'),styles:['zipper','drawstring','foldable','bowling','garment','postman'],uses:['cosmetic','shoe','suit','computer','bicycle','promotion','glasses'],
    points:[t('Specify fabric denier and finish; confirm whether a lining or backing is needed.','确认面料纤度与表面处理，明确是否需要内衬或背涂。','Defina denier y acabado, y si necesita forro o respaldo.'),t('Review zipper gauge, puller, seam allowances and internal pocket dimensions.','核对拉链规格、拉头、缝份与内袋尺寸。','Revise tamaño de cremallera, tirador, márgenes de costura y bolsillos.'),t('Test cleaning, abrasion and colour transfer in the actual intended use.','结合真实使用方式检查清洁、耐磨与颜色迁移。','Evalúe limpieza, abrasión y transferencia de color para el uso previsto.')],
    q:t('Is a polyester bag waterproof?','涤纶袋是否防水？','¿Una bolsa de poliéster es impermeable?'),a:t('Not by material name alone. Coatings, seams and closures determine water resistance. Specify the exposure and acceptance test; a coated fabric does not automatically make the complete bag watertight.','不能仅凭材质名称判断。涂层、接缝与封口共同影响防水表现，应明确接触水的条件和验收测试；面料有涂层不代表整袋不渗水。','El nombre del material no basta. Revestimientos, costuras y cierres determinan la resistencia al agua. Defina exposición y ensayo; un tejido recubierto no garantiza una bolsa estanca.'),source:'custom-metallic-polyester-cosmtic-bag.html',
  },
  {
    slug:'cotton-canvas-bags',category:'cotton-canvas',name:t('Custom cotton & canvas tote bags','定制棉布与帆布手提袋','Bolsas de algodón y lona personalizadas'),
    intro:t('Cotton and canvas totes offer a textile surface for retail, events and branded gifts. Compare fabric weight, weave, gusset and handle drop, then review artwork and cleaning expectations on a sample.','棉布与帆布手提袋适用于零售、活动及品牌礼赠的织物包装方向。选型时比较克重、织法、底侧宽与提手垂高，并用样品核对图稿与清洁要求。','Las bolsas de algodón y lona ofrecen una superficie textil para comercio, eventos y regalos. Compare gramaje, tejido, fuelle y caída de asas; revise impresión y limpieza con una muestra.'),
    material:t('Cotton / canvas; fiber blend and GSM or oz/yd² to confirm','棉布 / 帆布；成分、GSM 或 oz/yd² 需确认','Algodón / lona; mezcla y GSM u oz/yd² por confirmar'),use:t('Retail · Events · Corporate gifts','零售 · 活动 · 企业礼赠','Comercio · Eventos · Regalos de empresa'),styles:['handle','postman','drawstring','beach','round','zipper'],uses:['shopping','promotion','wine','shoe','cosmetic'],
    points:[t('Specify composition and fabric weight with units. Canvas describes a construction, not a guarantee of pure cotton.','明确成分与克重单位；“帆布”描述织物结构，不自动代表纯棉。','Indique composición y unidades de gramaje. La lona describe una construcción, no garantiza algodón puro.'),t('Measure handle drop and usable dimensions after seams; check the fit with the intended contents.','测量缝制后的可用尺寸与提手垂高，装入实际物品核对。','Mida caída de asas y espacio útil tras la confección; pruebe el contenido real.'),t('Agree on shrinkage, colourfastness and print care before using a washable claim.','宣称可洗前，确认缩水、色牢度与印刷护理要求。','Acuerde encogimiento, solidez del color y cuidado de la impresión antes de afirmar que es lavable.')],
    q:t('Which canvas weight should I choose?','帆布袋应该选多厚？','¿Qué gramaje de lona conviene elegir?'),a:t('Choose against contents, desired structure and packing volume. Higher fabric weight changes the hand feel but does not independently establish load capacity. Compare samples with your artwork, handles and intended load.','根据内装物、所需挺度和装箱体积选择。较高克重会改变手感，但不能单独证明承重。应结合图稿、提手与实际负载比较样品。','Elija según contenido, estructura deseada y volumen de embalaje. Un mayor gramaje cambia el tacto, pero no determina por sí solo la carga admisible. Compare muestras con su impresión, asas y carga.'),source:'heavy-duty-canvas-shouler-bag.html',
  },
  {
    slug:'reflective-bags',category:'reflective',name:t('Custom reflective fabric bags','定制反光面料袋','Bolsas de tejido reflectante personalizadas'),
    intro:t('Reflective fabric creates a distinctive surface for promotional bags and accessory projects. Define panel placement, base fabric and print coverage, and separate decorative appearance from tested visibility requirements.','反光面料为促销袋与配件项目提供特殊表面效果。需明确面料基底、拼片位置与印刷覆盖，并区分装饰效果和经过测试的可视性要求。','El tejido reflectante aporta un acabado particular a bolsas promocionales y accesorios. Defina soporte, paneles e impresión y distinga la decoración de los requisitos de visibilidad ensayados.'),
    material:t('Reflective surface on a specified textile backing','反光表层与指定织物基底','Superficie reflectante sobre soporte textil definido'),use:t('Promotions · Cycling accessories · Drawstring bags','促销 · 骑行配件 · 抽绳袋','Promoción · Accesorios ciclistas · Bolsas de cordón'),styles:['drawstring','zipper','handle','postman'],uses:['reflective','bicycle','promotion','computer'],
    points:[t('Define reflective coverage and whether the application is decorative or has a visibility specification.','明确反光覆盖范围，以及用途属于装饰还是有可视性指标。','Defina cobertura y si el uso es decorativo o exige visibilidad específica.'),t('Check flexing, abrasion and repeated cleaning on the finished surface.','核对表层反复弯折、摩擦与清洁后的表现。','Compruebe flexión, abrasión y limpiezas repetidas del acabado.'),t('Review printing locations so graphics do not unintentionally cover the reflective area.','核对印刷位置，避免图案意外遮盖反光区域。','Revise la ubicación de gráficos para no cubrir accidentalmente la zona reflectante.')],
    q:t('Is a reflective bag certified safety equipment?','反光袋就是经过认证的安全装备吗？','¿Una bolsa reflectante es un equipo de seguridad certificado?'),a:t('No. A reflective appearance is not evidence of certification or protective performance. If a safety use is required, specify the applicable standard and obtain relevant testing for the complete product.','不是。反光外观不能证明认证或防护性能。若用于安全防护，应明确适用标准，并取得完整产品的相关测试依据。','No. El aspecto reflectante no acredita certificación ni protección. Para un uso de seguridad, defina la norma aplicable y solicite ensayos del producto completo.'),source:'reflective-8.html',
  },
  {
    slug:'felt-bags',category:'felt',name:t('Custom felt bags & organizers','定制毛毡袋与收纳包','Bolsas y organizadores de fieltro personalizados'),
    intro:t('Felt gives totes, storage organizers and sleeves a structured textile appearance. Specify fiber composition, thickness and edge treatment, then check the fit and surface wear with the intended contents.','毛毡可用于有结构感的手提袋、收纳件与保护套。需确认纤维成分、厚度和边缘处理，再按内装物核对尺寸与表面磨损。','El fieltro aporta estructura a bolsas, organizadores y fundas. Especifique composición, espesor y bordes, y compruebe ajuste y desgaste con el contenido previsto.'),
    material:t('Felt; fiber composition, thickness and density to confirm','毛毡；纤维成分、厚度与密度待确认','Fieltro; composición, espesor y densidad por confirmar'),use:t('Storage · Gifts · Laptop sleeves','收纳 · 礼赠 · 电脑套','Almacenaje · Regalos · Fundas de portátil'),styles:['handle','basket','zipper','round'],uses:['storage','computer','wine','glasses','promotion','shopping'],
    points:[t('Confirm whether the felt is polyester, wool or a blend; thickness does not identify its composition.','确认是涤纶、羊毛还是混纺毛毡，厚度不能说明成分。','Confirme si es poliéster, lana o mezcla; el espesor no identifica la composición.'),t('Check pilling, edge shedding and stitch appearance on the chosen colour.','核对所选颜色的起球、边缘掉纤与缝线外观。','Revise formación de bolitas, desprendimiento de fibras y aspecto de las costuras.'),t('For sleeves, specify internal clearance and closure protection; do not infer impact protection from thickness.','保护套需确认内部余量及封口防护，不能凭厚度推测抗冲击能力。','En fundas, defina holgura y protección del cierre; no deduzca resistencia al impacto del espesor.')],
    q:t('Does felt always mean wool?','毛毡一定是羊毛的吗？','¿El fieltro siempre es de lana?'),a:t('No. Felt can use different fibers, including polyester and wool. Ask for the actual composition and care instructions, especially when fiber labeling or washing requirements matter.','不是。毛毡可以使用涤纶、羊毛等不同纤维。应索取实际成分和护理说明，尤其是有纤维标签或洗涤要求时。','No. Puede estar hecho de distintas fibras, como poliéster o lana. Solicite composición e instrucciones de cuidado, especialmente si hay requisitos de etiquetado o lavado.'),source:'fashionable-felt-tote-bag.html',
  },
  {
    slug:'paper-washable-paper-bags',category:'paper',name:t('Custom paper & washable paper bags','定制纸袋与水洗纸袋','Bolsas de papel y papel lavable personalizadas'),
    intro:t('Paper and washable-paper designs cover different packaging needs. Start by specifying the paper grade or composite, handle attachment and wet-use expectations for retail bags, gift packaging and pouches.','普通纸袋与水洗纸袋对应不同包装需求。开发零售手提袋、礼品包装与收纳包时，应先明确纸种或复合成分、提手连接及遇水使用要求。','El papel convencional y el papel lavable cubren necesidades diferentes. Defina calidad o compuesto, fijación de asas y exposición al agua para bolsas comerciales, regalos y estuches.'),
    material:t('Paper or washable-paper composite; grade to confirm','纸张或水洗纸复合材料；具体等级需确认','Papel o compuesto de papel lavable; calidad por confirmar'),use:t('Retail · Gift packaging · Pouches','零售 · 礼品包装 · 收纳袋','Comercio · Regalos · Estuches'),styles:['handle','zipper','round','basket'],uses:['shopping','promotion','cosmetic','storage'],
    points:[t('Distinguish ordinary kraft paper from a washable composite and confirm coatings or binders.','区分普通牛皮纸和可水洗复合材料，确认涂层或粘结成分。','Distinga papel kraft convencional de un compuesto lavable y confirme recubrimientos y aglutinantes.'),t('Specify creasing, folding and handle attachment; inspect stress at punched holes and seams.','明确压痕、折叠与提手连接方式，检查冲孔及接缝受力。','Defina hendido, plegado y fijación de asas; revise tensión en perforaciones y costuras.'),t('Agree on wash method, drying and dimensional change if washing is required.','如有水洗要求，需约定洗法、干燥方式与尺寸变化验收。','Si se requiere lavado, acuerde método, secado y cambio dimensional admisible.')],
    q:t('Can any kraft paper bag be washed?','牛皮纸袋都能水洗吗？','¿Se puede lavar cualquier bolsa de papel kraft?'),a:t('No. Washability depends on the specific material and complete construction. Confirm a care method and test a finished sample. The term “washable paper” alone is not a test result or a recycling guarantee.','不能。可水洗性取决于具体材料和整袋结构，应确认护理方式并测试成品样品。“水洗纸”名称本身不等于测试结果或可回收保证。','No. Depende del material y de la confección completa. Confirme el cuidado y ensaye una muestra terminada. “Papel lavable” no constituye un resultado de ensayo ni garantiza reciclabilidad.'),source:'washable-kraft-paper-tote-bag.html',
  },
  {
    slug:'glitter-metallic-bags',category:'glitter',name:t('Custom glitter & metallic finish bags','定制闪光与金属效果袋','Bolsas con purpurina y acabado metalizado'),
    intro:t('Glitter and metallic finishes add a decorative surface to gift bags and promotional packaging. Specify the base material and finish separately, with particular attention to rubbing, folding and print adhesion.','闪光与金属效果为礼品袋及促销包装提供装饰表面。基材与表面工艺需要分别确认，重点核对摩擦、折叠与印刷附着表现。','Los acabados con purpurina y metalizados decoran bolsas de regalo y promoción. Defina soporte y acabado por separado, atendiendo a roce, pliegues y adherencia de la impresión.'),
    material:t('Textile or non-woven base with a decorative finish','织物或无纺布基材 + 装饰表层','Soporte textil o no tejido con acabado decorativo'),use:t('Gifts · Events · Cosmetic packaging','礼赠 · 活动 · 化妆品包装','Regalos · Eventos · Cosméticos'),styles:['handle','postman','zipper','round'],uses:['promotion','cosmetic','shopping'],
    points:[t('Choose particle glitter, metallic film or coated fabric explicitly; they are different constructions.','明确选择颗粒闪粉、金属效果膜或涂层布，三者结构不同。','Distinga purpurina en partículas, película metalizada y tejido recubierto.'),t('Check surface shedding, fold cracking and colour transfer against the agreed sample.','按确认样品检查表面脱落、折痕开裂与颜色迁移。','Revise desprendimiento, grietas en pliegues y transferencia de color frente a la muestra aprobada.'),t('Review ink adhesion and hardware colour under the intended lighting.','在实际使用光线下核对油墨附着与五金颜色。','Revise adherencia de tinta y color de herrajes con la iluminación prevista.')],
    q:t('Are metallic bags the same as insulated foil bags?','金属效果袋与铝箔保温袋一样吗？','¿Una bolsa metalizada equivale a una bolsa térmica de aluminio?'),a:t('No. A metallic decorative finish does not establish an insulation function. For thermal packaging, specify the full insulating layer structure and test the packed system.','不一样。金属装饰效果不能说明保温功能。温控包装需要明确完整隔热层结构，并测试装好产品后的包装系统。','No. Un acabado decorativo metalizado no demuestra aislamiento. Para embalaje térmico, especifique todas las capas aislantes y ensaye el sistema cargado.'),source:'non-woven-bag-72.html',
  },
  {
    slug:'tyvek-bags',category:'tyvek',name:t('Custom Tyvek material bags','定制 Tyvek 材料袋','Bolsas a medida con material Tyvek'),
    intro:t('Tyvek material is an option for lightweight, paper-like bag designs. Confirm the authentic material grade, hand feel, printing method and seam construction before approving a tote or pouch project.','Tyvek 材料可作为轻量纸感袋型的选材方向。开发手提袋或收纳包时，需核对材料真伪、具体等级、手感、印刷工艺和接缝结构。','Tyvek es una opción para diseños ligeros con aspecto de papel. Confirme autenticidad, calidad, tacto, impresión y costuras antes de aprobar una bolsa o estuche.'),
    material:t('Tyvek grade to verify; HDPE-based sheet material','Tyvek 等级需核实；HDPE 基片材','Calidad de Tyvek por verificar; lámina a base de HDPE'),use:t('Retail · Travel pouches · Gifts','零售 · 旅行收纳 · 礼赠','Comercio · Estuches de viaje · Regalos'),styles:['handle','zipper','foldable','postman'],uses:['shopping','promotion','cosmetic','computer'],
    points:[t('Request the exact grade and sourcing documents before specifying the Tyvek name.','指定 Tyvek 名称前，索取具体等级和采购来源文件。','Solicite calidad exacta y documentación de origen antes de especificar el nombre Tyvek.'),t('Confirm ink compatibility, crease appearance and seam reinforcement on samples.','用样品确认油墨适配、折痕外观和接缝加固。','Confirme compatibilidad de tinta, aspecto de pliegues y refuerzos con muestras.'),t('Review care instructions and the effect of coatings, linings and trims on disposal.','核对护理方式，以及涂层、内衬和辅料对处理方式的影响。','Revise cuidado y efecto de recubrimientos, forros y accesorios sobre la gestión al final de uso.')],
    q:t('Is Tyvek ordinary paper?','Tyvek 是普通纸吗？','¿Tyvek es papel convencional?'),a:t('No. Tyvek is a trademarked HDPE-based material with a paper-like appearance. Confirm the grade and authenticity; do not describe a bag as paper-recyclable or biodegradable based on its appearance.','不是。Tyvek 是具有纸感外观的 HDPE 基品牌材料。应核对等级与真伪，不能凭外观宣称可按纸回收或可生物降解。','No. Tyvek es una marca de material basado en HDPE con aspecto de papel. Confirme calidad y autenticidad; no afirme que se recicla como papel o es biodegradable por su apariencia.'),source:'tyvek-17.html',
  },
  {
    slug:'pvc-tpu-bags',category:'pvc-tpu',name:t('Custom PVC & TPU bags','定制 PVC 与 TPU 袋','Bolsas de PVC y TPU personalizadas'),
    intro:t('PVC and TPU offer different film options for transparent, tinted and decorative pouches. Specify the polymer, thickness, closure and target-market material requirements for cosmetics, travel or retail display.','PVC 与 TPU 是透明、着色及装饰收纳袋的不同膜材选项。用于化妆品、旅行或零售展示时，应明确聚合物种类、厚度、封口与目标市场材料要求。','PVC y TPU son opciones de película distintas para estuches transparentes, tintados o decorativos. Defina polímero, espesor, cierre y requisitos del mercado para cosmética, viaje o exposición.'),
    material:t('PVC or TPU film; not interchangeable','PVC 或 TPU 膜材；两者不可混称','Película de PVC o TPU; no son intercambiables'),use:t('Cosmetics · Travel · Retail display','化妆收纳 · 旅行 · 零售展示','Cosméticos · Viaje · Exposición'),styles:['zipper','handle','round','beach'],uses:['cosmetic','shopping','glasses','promotion'],
    points:[t('Specify polymer and thickness in millimetres, plus clarity, colour and surface finish.','明确聚合物与毫米厚度，以及透明度、颜色和表面效果。','Indique polímero y espesor en milímetros, transparencia, color y acabado.'),t('Check welded or sewn edges, zipper operation and blocking during storage.','检查热合或车缝边缘、拉链开合及储存粘连。','Revise bordes soldados o cosidos, cremallera y adherencia entre superficies al almacenar.'),t('Request material documentation relevant to destination restrictions and the intended contents.','按目的地限制与内装物用途索取材料文件。','Solicite documentación según restricciones del destino y contenido previsto.')],
    q:t('Can PVC and TPU be quoted as the same material?','PVC 与 TPU 可以按同一材料报价吗？','¿Se pueden cotizar PVC y TPU como el mismo material?'),a:t('No. They are different polymers and may differ in formulation, processing and cost. Compare quotations using the same polymer, thickness, construction and compliance scope.','不能。它们是不同聚合物，配方、加工方式和成本可能不同。比较报价时应统一聚合物、厚度、结构与合规范围。','No. Son polímeros distintos y pueden variar en formulación, proceso y coste. Compare cotizaciones con el mismo polímero, espesor, construcción y alcance documental.'),source:'small-tpu-makeup-bag.html',
  },
  {
    slug:'mesh-bags',category:'mesh',name:t('Custom cotton & polyester mesh bags','定制棉网袋与涤纶网袋','Bolsas de malla de algodón y poliéster'),
    intro:t('Open-mesh designs suit shopping, beach and storage projects where visibility and airflow are part of the brief. Specify fiber composition, mesh aperture, solid panels and closures around the smallest item carried.','网眼结构适合需要可视与通风设计的购物、沙滩及收纳项目。应根据最小内装物，确认纤维成分、网孔大小、实布拼片和封口方式。','La malla abierta permite visibilidad y ventilación en proyectos de compras, playa y almacenaje. Defina fibras, tamaño de abertura, paneles y cierre según el objeto más pequeño.'),
    material:t('Cotton or polyester mesh; optional solid fabric panels','棉或涤纶网布；可讨论实布拼片','Malla de algodón o poliéster; paneles textiles opcionales'),use:t('Shopping · Beach · Produce organization','购物 · 沙滩 · 果蔬整理','Compras · Playa · Organización de productos'),styles:['handle','drawstring','beach','foldable'],uses:['shopping','supermarket','shoe','storage'],
    points:[t('Match the mesh aperture to contents so small items cannot pass through.','网孔需匹配内装物，避免小件漏出。','Ajuste la abertura para evitar que se salgan objetos pequeños.'),t('Use solid panels or labels for artwork where mesh cannot support the intended detail.','网布不适合呈现细节的图稿，可讨论实布拼片或标签。','Considere paneles o etiquetas para gráficos que la malla no pueda reproducir.'),t('Check seam stretch, handle attachment and any cleaning or food-contact requirements.','检查接缝拉伸、提手连接，以及清洁或食品接触要求。','Compruebe estiramiento de costuras, asas y requisitos de limpieza o contacto alimentario.')],
    q:t('Can a mesh bag carry unpackaged produce?','网袋能直接装散装果蔬吗？','¿Puede una bolsa de malla llevar frutas sin envasar?'),a:t('Define the intended contact first. Review the fiber, dyes and any treatments against applicable food-contact requirements. An open weave alone does not establish food-contact suitability.','需要先明确直接接触用途，并按适用要求核对纤维、染料及处理剂。网眼结构本身不能证明适合食品接触。','Defina primero el contacto previsto. Revise fibras, tintes y tratamientos frente a los requisitos aplicables. El tejido abierto no demuestra por sí solo aptitud para contacto alimentario.'),source:'mesh-cotton-tote-bag.html',
  },
  {
    slug:'jute-bags',category:'jute',name:t('Custom jute tote & gift bags','定制黄麻手提袋与礼品袋','Bolsas de yute para compras y regalos'),
    intro:t('Jute provides a visible natural-fiber texture for retail totes, bottle bags and gift packaging. Compare the weave, cotton panels, lining and handles to balance appearance, artwork and carrying requirements.','黄麻为零售手提袋、酒瓶袋和礼品包装提供鲜明的天然纤维纹理。开发时可比较织法、棉布拼片、内衬与提手，兼顾外观、图稿及提携要求。','El yute aporta textura de fibra natural a bolsas comerciales, portabotellas y regalos. Compare tejido, paneles de algodón, forro y asas para equilibrar apariencia, impresión y transporte.'),
    material:t('Jute; blends, lining and lamination to confirm','黄麻；混纺、内衬与覆膜需确认','Yute; mezclas, forro y laminado por confirmar'),use:t('Retail · Wine packaging · Gifts','零售 · 酒瓶包装 · 礼赠','Comercio · Botellas de vino · Regalos'),styles:['handle','basket','beach','zipper'],uses:['shopping','wine','promotion','supermarket'],
    points:[t('Specify jute content, weave openness and whether the interior is laminated.','确认黄麻比例、织物疏密与内部是否覆膜。','Especifique proporción de yute, apertura del tejido y laminado interior.'),t('Review small print details on the textured surface; a cotton panel can change the print result.','在纹理表面核对小字效果，棉布拼片会形成不同印刷表现。','Revise detalles pequeños sobre la textura; un panel de algodón cambia el resultado.'),t('Check storage humidity, odor and handle comfort using the intended contents.','结合内装物核对储存湿度、气味与提手舒适性。','Compruebe humedad de almacenamiento, olor y comodidad de asas con el contenido previsto.')],
    q:t('Is a laminated jute bag plastic-free?','覆膜黄麻袋是不含塑料的吗？','¿Una bolsa de yute laminada está libre de plástico?'),a:t('Not necessarily. Linings, lamination, threads and trims can contain synthetic materials. A plastic-free claim needs a complete bill of materials, not just a natural outer fabric.','不一定。内衬、覆膜、缝线和辅料可能含合成材料。“不含塑料”需要完整材料清单支持，不能仅凭天然外层面料判断。','No necesariamente. Forros, laminados, hilos y accesorios pueden contener materiales sintéticos. Una declaración sin plástico necesita la lista completa de materiales.'),source:'jute-bag-with-magnetic-button-inside-03.html',
  },
  {
    slug:'bamboo-fiber-bags',category:'bamboo',name:t('Custom bamboo-derived fiber bags','定制竹来源纤维袋','Bolsas de fibra derivada de bambú'),
    intro:t('Bamboo-derived fiber is a sourcing category that requires a clear fiber declaration. Define the actual material, processing route and blend before comparing shopping or promotional bag specifications.','竹来源纤维是需要明确纤维声明的选材类别。比较购物袋或促销袋方案前，应先确认实际材料、加工路径与混纺成分。','La fibra derivada de bambú requiere una declaración clara de composición. Defina material real, proceso y mezcla antes de comparar especificaciones para bolsas comerciales o promocionales.'),
    material:t('Bamboo-derived textile; actual fiber designation to verify','竹来源纺织材料；实际纤维名称需核实','Textil derivado de bambú; denominación real por verificar'),use:t('Shopping · Promotions · Gift packaging','购物 · 促销 · 礼品包装','Compras · Promoción · Regalos'),styles:['handle','drawstring','foldable'],uses:['shopping','promotion','supermarket'],
    points:[t('Distinguish mechanically processed bamboo fiber from regenerated cellulose such as viscose.','区分机械加工竹纤维与粘胶等再生纤维素纤维。','Distinga fibra de bambú procesada mecánicamente de celulosa regenerada, como viscosa.'),t('Confirm blend percentages, GSM and label wording for the destination market.','确认混纺比例、克重与目标市场纤维标签用语。','Confirme porcentajes de mezcla, gramaje y etiquetado para el mercado de destino.'),t('Evaluate shrinkage, seam strength and colourfastness on the finished sample.','用成品样品评估缩水、接缝强度与色牢度。','Evalúe encogimiento, resistencia de costura y solidez del color en la muestra terminada.')],
    q:t('Does bamboo origin prove antibacterial or biodegradable performance?','竹来源就能证明抗菌或可降解吗？','¿El origen de bambú demuestra propiedades antibacterianas o biodegradables?'),a:t('No. Feedstock origin does not verify those properties. Claims need evidence for the actual processed material and finished construction under stated conditions.','不能。原料来源不能证明这些性能，相关表述需要实际加工材料与成品结构在明确条件下的证据。','No. El origen de la materia prima no verifica esas propiedades. Las afirmaciones necesitan evidencia del material procesado y de la construcción terminada bajo condiciones definidas.'),source:'Bamboo%20Fiber%20Bag-001.html',
  },
  {
    slug:'leather-bags',category:'leather',name:t('Custom leather & alternative-material bags','皮革及替代材料袋定制评估','Bolsas de cuero y materiales alternativos a medida'),
    intro:t('Develop a bag brief around genuine leather, coated textile or another specified alternative. Material availability and construction feasibility are reviewed against your sample, artwork and intended use before quotation.','可围绕真皮、涂层织物或指定替代材料提出开发需求。报价前需结合样品、图稿和实际用途评估材料可得性及结构可行性。','Desarrolle un proyecto con cuero, textil recubierto u otra alternativa definida. La disponibilidad y viabilidad de confección se revisan según muestra, diseño y uso antes de cotizar.'),
    material:t('Genuine leather or specified alternative; feasibility review required','真皮或指定替代材料；需评估可行性','Cuero o alternativa definida; requiere evaluación'),use:t('Accessories · Pouches · Corporate gifts','配件 · 收纳包 · 企业礼赠','Accesorios · Estuches · Regalos de empresa'),styles:['handle','postman','zipper','round'],uses:['cosmetic','computer','glasses','promotion'],
    points:[t('State genuine leather, PU-coated textile or another composition explicitly; avoid ambiguous leather labels.','明确是真皮、PU 涂层织物还是其他成分，避免模糊使用“皮革”标签。','Indique cuero, textil recubierto de PU u otra composición; evite etiquetas ambiguas.'),t('Specify thickness, backing, lining, edge paint and hardware before sample development.','打样前确认厚度、基底、内衬、边油及五金。','Defina espesor, soporte, forro, pintura de cantos y herrajes antes del desarrollo.'),t('Review abrasion, flexing and colour transfer; compare the finished construction rather than surface swatches alone.','检查耐磨、弯折及颜色迁移，应比较成品结构而非仅表面色卡。','Revise abrasión, flexión y transferencia de color en la construcción terminada, no solo en retales.')],
    q:t('What is needed to develop a leather-look bag?','开发皮革外观袋需要什么资料？','¿Qué se necesita para desarrollar una bolsa con aspecto de cuero?'),a:t('Provide a reference sample or drawing, the required composition, dimensions, hardware and destination requirements. The term leather-look describes appearance only; composition, supply and manufacturing feasibility must be confirmed separately.','请提供参考样或图纸、要求的成分、尺寸、五金和目标市场要求。“皮革外观”只描述外观，实际成分、供料与生产可行性需单独确认。','Facilite muestra o plano, composición requerida, medidas, herrajes y requisitos del destino. El aspecto de cuero solo describe la apariencia; composición, suministro y viabilidad se confirman por separado.'),
  },
  {
    slug:'other-custom-bags',category:'other',name:t('Other custom bag materials & formats','其他材质与特殊袋型定制','Otros materiales y formatos de bolsas a medida'),
    intro:t('Use this development route for a material, hybrid construction or format outside the standard families. Start with a physical reference or drawing and a clear use case so sourcing, sampling and testing can be scoped together.','对于常规系列之外的材质、复合结构或特殊袋型，可从此提交开发需求。先提供实物参考或图纸与明确用途，以便共同界定选材、打样和测试范围。','Para materiales, construcciones mixtas o formatos fuera de las familias habituales, comparta una referencia o plano y un uso claro para definir suministro, muestras y ensayos.'),
    material:t('Specified by the project; material and process review required','按项目指定；需评估材料与工艺','Según proyecto; requiere revisión de material y proceso'),use:t('Special packaging · New product development','特殊包装 · 新品开发','Embalaje especial · Desarrollo de producto'),styles:['other','bowling','garment','basket','round'],uses:['other','beach-mat','garbage','storage','bicycle'],
    points:[t('Supply a reference, drawing or material sample with usable dimensions and closure details.','提供参考款、图纸或材料样，并说明可用尺寸与封口细节。','Aporte referencia, plano o muestra de material con medidas útiles y cierre.'),t('Prioritize required functions and distinguish them from optional features to control development scope.','区分必须功能与可选配置，明确开发范围。','Priorice funciones obligatorias frente a opciones para delimitar el desarrollo.'),t('Agree on feasibility, sampling costs, test methods and acceptance criteria before committing to production.','投产前确认可行性、打样费用、测试方法与验收标准。','Acuerde viabilidad, costes de muestras, métodos de ensayo y criterios de aceptación antes de producir.')],
    q:t('Can you quote from a reference picture alone?','只有一张参考图能准确报价吗？','¿Se puede cotizar con precisión solo con una foto?'),a:t('A picture can start the discussion, but it does not define hidden layers, usable dimensions, material grades or performance. A comparable quotation needs those details plus quantity, artwork, packing and delivery requirements.','参考图可以启动沟通，但不能定义隐藏层、可用尺寸、材料等级或性能。可比较的报价还需要这些细节，以及数量、图稿、包装和交货要求。','Una foto inicia la conversación, pero no define capas ocultas, medidas útiles, calidades ni prestaciones. Una cotización comparable requiere esos detalles, cantidad, diseño, embalaje y entrega.'),
  },
]

export const extraBags:Bag[] = entries.map(e=>({
  slug:e.slug,category:e.category,name:e.name,short:e.name,intro:e.intro,material:e.material,use:e.use,
  group:'shopping',color:'#617b8c',type:'box',styles:e.styles,uses:e.uses,considerations:e.points,question:e.q,answer:e.a,
  ...(e.source?{source:e.source,image:`${e.slug}.webp`}:{}),
}))
