import { tx, type Lang } from './data'
import { stockFor, type CommercialProfile } from './commercial-data'

type Props={profile:CommercialProfile;lang:Lang}
export function OrderOptions({profile,lang}:Props){
 return <><p>{tx('Choose the order method before comparing quantities. Each minimum applies to the stated size, thickness and printing conditions.','先确定订购方式，再比较起订量。各门槛须结合对应尺寸、厚度和印刷条件使用。','Elija el método de pedido antes de comparar cantidades. Cada mínimo depende de las medidas, espesor e impresión indicados.')[lang]}</p><div className="order-options">{profile.options.map((o,i)=><article key={o.name.en}><span className="eyebrow">0{i+1}</span><h3>{o.name[lang]}</h3><div className="order-minimum"><span>{tx('Minimum order','最低起订量','Pedido mínimo')[lang]}</span><strong>{o.moq[lang]}</strong></div><p>{o.scope[lang]}</p>{o.notes&&<p className="order-exception">{o.notes[lang]}</p>}</article>)}</div></>
}
export function CommercialLeadTimes({profile,lang}:Props){
 return <><div className="commercial-schedule">{profile.options.map(o=><article key={o.name.en}><h3>{o.name[lang]}</h3><div><span>{tx('Samples & approval','打样与确认','Muestras y aprobación')[lang]}</span><p>{o.sample[lang]}</p></div><div><span>{tx('Production / dispatch','生产／发货','Producción / despacho')[lang]}</span><strong>{o.lead[lang]}</strong></div></article>)}</div><p className="technical-note">{tx('Listed production periods exclude transport and customs clearance. Confirm artwork approval, the start date, sample charges, freight and the dispatch schedule in the quotation. Stock availability is checked when ordering.','以上生产交期不含运输和清关。电子效果图确认、交期起算条件、样品费、运费及具体出货日，应在报价和下单时确认；现货以订购时库存为准。','Los plazos de producción excluyen transporte y aduanas. Confirme aprobación del diseño, fecha de inicio, coste de muestras, flete y despacho en la cotización. Las existencias se comprueban al pedir.')[lang]}</p></>
}
export function StockSizes({profile,lang}:Props){
 const rows=stockFor(profile), isIce=profile.fixedSizes, isNonwoven=profile.stocks==='nonwoven'
 return <><h3>{tx('Available size options','可选规格明细','Opciones de medidas')[lang]}</h3><p>{profile.dimensions[lang]}</p>{profile.tolerance&&<p className="technical-note">{profile.tolerance[lang]}</p>}{profile.colors&&<p>{profile.colors[lang]}</p>}
 <div className="stock-table-scroll" tabIndex={0} role="region" aria-label={tx('Size options table','可选尺寸表','Tabla de medidas')[lang]}><table className="stock-size-table"><caption>{tx('Dimensions in cm · Confirm inventory before ordering','尺寸单位：cm · 下单前确认库存','Medidas en cm · Confirmar existencias antes de pedir')[lang]}</caption><thead><tr><th scope="col">{tx('Size','尺寸','Medidas')[lang]} (cm)</th><th scope="col">{isNonwoven?tx('Size option','规格名称','Formato')[lang]:isIce?tx('Capacity / cells','容量／格数','Capacidad / celdas')[lang]:tx('Thickness','厚度','Espesor')[lang]}</th></tr></thead><tbody>{rows.map(r=><tr key={r.dimensions+r.capacity}><td>{r.dimensions}</td><td>{isNonwoven?r.sizeLabel?.[lang]:isIce?(profile.stocks==='segmented'?`${r.capacity} ${tx('cells','格','celdas')[lang]}`:r.capacity):(r.thickness||tx('Confirm material specification','按材质规格确认','Confirmar especificación')[lang])}</td></tr>)}</tbody></table></div>
 <p className="technical-note">{tx('These are size options, not a live inventory feed. Stock and custom-print order minimums are listed separately above.','此表展示规格选项，不代表实时库存；现货与定制印刷起订量请分别查看上方订购条件。','Estas son opciones de medida, no inventario en tiempo real. Los mínimos de existencias e impresión se indican por separado arriba.')[lang]}</p></>
}
