import type { Text } from './data'
import stockData from './stock-specifications.json'

const t = (en: string, zh: string, es: string): Text => ({ en, zh, es })
export type OrderOption = { name: Text; moq: Text; scope: Text; sample: Text; lead: Text; notes?: Text }
export type CommercialProfile = { sourceRows: number[]; options: OrderOption[]; moq: Text; sample: Text; lead: Text; dimensions: Text; tolerance?: Text; fixedSizes?: boolean; stocks: string; colors?: Text }
const stockMOQ=t('100 pcs per size and thickness','同规格、同厚度 100 个','100 unidades por medida y espesor')
const stockSample=t('Stock samples available to purchase; price by quotation.','可购买现货样品，费用按现货报价。','Muestras de existencias disponibles para compra; precio según cotización.')
const stockLead=t('Subject to available inventory','按实际库存确认发货','Despacho según existencias disponibles')
const handSample=t('Handmade sample: CNY 10–20; dispatched in 1–2 days. Machine-made orders also use handmade samples; construction may differ.','手工样品 10–20 元，1–2 天寄出。机器大货也以手工样确认，工艺存在差异。','Muestra manual: 10–20 CNY; despacho en 1–2 días. Los pedidos mecanizados también usan muestras manuales; la fabricación puede diferir.')
const foilLead=t('Unprinted: 5–7 days; printed: 10–15 days','无印刷 5–7 天；印刷 10–15 天','Sin impresión: 5–7 días; impresos: 10–15 días')
const foilPrint=t('Single-colour screen-printed logo; printed orders start at 2,000 pcs. Approve the digital artwork before production.','单色 LOGO 丝印，印刷订单 2,000 个起；确认电子效果图后生产。','Logotipo serigrafiado a un color; pedidos impresos desde 2.000 unidades. Aprobar el diseño digital antes de producir.')
const foilTolerance=t('Dimensions approximately ±1 cm; thickness approximately ±0.2 mm.','尺寸约 ±1 cm，厚度约 ±0.2 mm。','Medidas aproximadamente ±1 cm; espesor aproximadamente ±0,2 mm.')
const stockOption=(scope:Text):OrderOption=>({name:t('Stock, unprinted','无印刷现货','Existencias sin impresión'),moq:stockMOQ,scope,sample:stockSample,lead:stockLead})
const flatMOQ=t('Custom size: about 500 pcs for larger sizes or 1,000 for smaller sizes; factory assessment required. Printed: 2,000 pcs.','定制尺寸：大尺寸约 500 个，小尺寸约 1,000 个，具体由工厂评估；印刷 2,000 个起。','Medida a pedido: unas 500 unidades para tamaños grandes o 1.000 para pequeños, sujeto a evaluación. Impresión: 2.000 unidades.')
const flatNotes=t('No fixed size threshold separates large and small formats. At 3.8 mm, the minimum is 1,000 pcs; printed orders still require 2,000 pcs.','大、小尺寸没有固定分界。3.8 mm 厚度 1,000 个起，印刷仍需 2,000 个起。','No hay un límite fijo entre formatos grandes y pequeños. Para 3,8 mm: mínimo 1.000 unidades; con impresión siguen siendo 2.000.')
const flatCustom:OrderOption={name:t('Custom size / printed','定制尺寸／印刷','Medida a pedido / impresión'),moq:flatMOQ,scope:foilPrint,sample:handSample,lead:foilLead,notes:flatNotes}
const flatDimensions=t('Dimensions are in cm. Confirm the measurement direction and usable internal space with your filled contents.','尺寸单位为 cm；结合装好后的内装物，确认测量方向与可用内部空间。','Medidas en cm. Confirme la orientación de medida y el espacio útil con el contenido lleno.')
const foilSummary=t('Stock: 100 pcs per specification. Custom quantity varies by size, thickness and printing.','现货同规格 100 个起；定制起订量按尺寸、厚度与印刷区分。','Existencias: 100 unidades por especificación. Mínimo a pedido según medida, espesor e impresión.')

const flat:CommercialProfile={sourceRows:[14,15],options:[stockOption(t('2 mm / 3 mm machine-made formats, plus four 3.8 mm handmade flat sizes.','2 mm／3 mm 机器平口，另有 4 款 3.8 mm 手工平口尺寸。','Formatos planos mecanizados de 2 / 3 mm y cuatro medidas manuales de 3,8 mm.')),flatCustom],moq:foilSummary,sample:handSample,lead:foilLead,dimensions:flatDimensions,tolerance:foilTolerance,stocks:'flat'}
const adhesive:CommercialProfile={...flat,sourceRows:[16,17],options:[stockOption(t('2 mm / 3 mm stock sizes. The adhesive flap adds 4 cm beyond the bag-body height.','2 mm／3 mm 现货尺寸；袋身高度之外另加 4 cm 折口。','Medidas de existencias de 2 / 3 mm. La solapa adhesiva añade 4 cm a la altura del cuerpo.')),flatCustom],dimensions:t('Width × bag-body height + 4 cm flap. For example, 15 × 20 + 4 cm means a 20 cm bag body plus a 4 cm flap.','宽 × 袋身高 + 4 cm 折口。例如 15 × 20 + 4 cm 中，袋身高为 20 cm，另加 4 cm 折口。','Ancho × altura del cuerpo + solapa de 4 cm. Por ejemplo, 15 × 20 + 4 cm indica cuerpo de 20 cm y solapa adicional de 4 cm.'),stocks:'adhesive'}
const manualMOQ=t('Custom size: 500 pcs; 3.8 mm: 1,000 pcs. Printed orders: 2,000 pcs.','定制尺寸 500 个起；3.8 mm 厚度 1,000 个起；印刷 2,000 个起。','Medida a pedido: 500 unidades; 3,8 mm: 1.000. Pedidos impresos: 2.000 unidades.')
const manual:CommercialProfile={sourceRows:[12,13],options:[stockOption(t('3.8 mm stock formats; confirm the size around your box.','3.8 mm 现货款，结合内装盒确认尺寸。','Formatos de existencias de 3,8 mm; confirme la medida con su caja.')),{name:t('Custom gusseted / cake bag','定制立体／蛋糕袋','Bolsa con base / pastelería a pedido'),moq:manualMOQ,scope:foilPrint,sample:handSample,lead:foilLead,notes:t('500–1,999 pcs use handmade construction; 2,000+ pcs may use machine production. The 3.8 mm minimum remains 1,000 pcs.','500–1,999 个采用手工工艺；2,000 个及以上可做机器款。3.8 mm 手工款仍为 1,000 个起。','De 500 a 1.999 unidades se fabrican manualmente; desde 2.000 puede usarse máquina. Para 3,8 mm el mínimo sigue siendo 1.000.')}],moq:manualMOQ,sample:handSample,lead:foilLead,dimensions:t('Three dimensions in cm, in catalogue order. Confirm measurement direction before ordering. Cake bags use gusseted formats selected to fit the cake box; confirm the fit with a sample.','三维尺寸按目录顺序列出，单位 cm；下单前确认测量方向。蛋糕袋按蛋糕盒选择立体规格，适配效果以样品确认。','Tres medidas en cm, en el orden del catálogo. Confirme la orientación al pedir. Las bolsas de pastelería usan formatos con base adaptados a la caja; confirme con una muestra.'),tolerance:foilTolerance,stocks:'manual'}
const machineMOQ=t('Custom size or printing: 2,000 pcs. Existing-size machine formats at 3.8 mm: 1,000 pcs; printed orders require 2,000.','定制尺寸或印刷 2,000 个起；现有尺寸 3.8 mm 机器款 1,000 个起，印刷仍为 2,000 个起。','Medida a pedido o impresión: 2.000 unidades. Formatos mecanizados existentes de 3,8 mm: 1.000; con impresión: 2.000.')
const machine:CommercialProfile={sourceRows:[10,11],options:[stockOption(t('16 standard sizes in 2 mm / 3 mm; machine-pressed edges and triangular corner finishing.','16 种标准尺寸，2 mm／3 mm；机械压边与三角收边。','16 medidas estándar de 2 / 3 mm; bordes prensados y acabado triangular en esquinas.')),{name:t('Machine-made customization','机器款定制','Personalización mecanizada'),moq:machineMOQ,scope:foilPrint,sample:handSample,lead:foilLead}],moq:machineMOQ,sample:handSample,lead:foilLead,dimensions:t('Three dimensions in cm, in catalogue order. Confirm measurement direction before ordering. Stock sizes below list the available 2 mm and 3 mm options.','三维尺寸按目录顺序列出，单位 cm；下单前确认测量方向。下表列出现货 2 mm 与 3 mm 规格。','Tres medidas en cm, en el orden del catálogo. Confirme la orientación al pedir. La tabla enumera las opciones de existencias de 2 y 3 mm.'),tolerance:foilTolerance,stocks:'machine'}

const noPhysical=t('Digital artwork approval only; no physical custom sample for this method.','此工艺仅确认电子效果图，不做定制实物样品。','Solo aprobación del diseño digital; este método no ofrece muestra física personalizada.')
const printLead=t('7–10 days','7–10 天','7–10 días')
const dedicatedSample=t('Fully custom orders: 1–2 digital-print samples for CNY 200–300, around 3–5 days. Digital samples and dedicated production may differ in colour and finish.','专版定制订单可做 1–2 个数码实物样，200–300 元，约 3–5 天；数码样与专版大货可能存在合理色差和效果差异。','Pedidos con diseño exclusivo: 1–2 muestras digitales por 200–300 CNY, unos 3–5 días. El color y acabado pueden diferir de la producción con diseño exclusivo.')
const nonwoven:CommercialProfile={sourceRows:[7,8,9],options:[
 {name:t('Stock bag + screen printing','现货加印 · 丝印','Bolsa existente + serigrafía'),moq:t('100 pcs','100 个','100 unidades'),scope:t('Five stock sizes and 13 bag colours. One print colour shared by front and back; limited print area. No custom dimensions.','5 种现货尺寸、13 种袋色；正反面统一单色丝印，印刷范围有限，不可改尺寸。','Cinco medidas y 13 colores de bolsa. Un mismo color de impresión en ambas caras; área limitada. Sin medidas a pedido.'),sample:noPhysical,lead:printLead},
 {name:t('Stock size + digital colour print','现货尺寸 · 数码彩印','Medida existente + impresión digital'),moq:t('200 pcs per regular size; extra large: 1,000 pcs','常规尺寸单款 200 个；特大号 1,000 个','200 unidades por medida regular; extragrande: 1.000'),scope:t('Full-bag digital artwork in one or multiple colours, using the five existing sizes. No custom dimensions.','可做全袋单色或多色图案；限 5 种现有尺寸，不可改尺寸。','Diseño digital a uno o varios colores en toda la bolsa, limitado a las cinco medidas existentes.'),sample:noPhysical,lead:printLead},
 {name:t('Fully custom production','专版定制','Producción con diseño exclusivo'),moq:t('5,000 pcs','5,000 个','5.000 unidades'),scope:t('Custom size, bag colour and full-bag artwork; unrestricted artwork colours. Approve the digital layout before production.','可定制尺寸、袋色和全袋图案，图案颜色不限；确认电子效果图后生产。','Medidas, color y diseño completo a pedido; colores de diseño sin límite. Aprobar el diseño digital antes de producir.'),sample:dedicatedSample,lead:t('15 days','15 天','15 días')}
],moq:t('Screen print: 100 pcs. Digital: 200 pcs, or 1,000 extra large. Fully custom: 5,000 pcs.','丝印 100 个；数码彩印常规 200 个／特大号 1,000 个；专版定制 5,000 个。','Serigrafía: 100 unidades. Digital: 200, o 1.000 extragrandes. Diseño exclusivo: 5.000.'),sample:dedicatedSample,lead:t('Stock-size printing: 7–10 days; fully custom: 15 days','现货尺寸加印 7–10 天；专版定制 15 天','Impresión en medidas existentes: 7–10 días; diseño exclusivo: 15 días'),dimensions:t('Five standard sizes in cm, shown in the supplied measurement order. Custom dimensions are available with fully custom production at 5,000 pcs.','5 种标准尺寸，单位 cm，按资料中的三维顺序列出。专版定制 5,000 个起可改尺寸。','Cinco medidas estándar en cm, en el orden dimensional de la ficha. Medidas a pedido disponibles con producción exclusiva desde 5.000 unidades.'),tolerance:t('Manual measurement: approximately 1–2 cm variation.','手工测量，尺寸误差约 1–2 cm。','Medición manual: variación aproximada de 1–2 cm.'),stocks:'nonwoven',colors:t('13 stock bag colours; request the current swatch card to confirm the shade.','13 种现货袋色，具体颜色以当前色卡确认。','13 colores de bolsa; solicite la carta actual para confirmar el tono.')}

const iceMOQ=t('Stock: 100 pcs per specification. Custom printing: 100,000 pcs per design.','现货同规格 100 个起；专版印刷单款 100,000 个起。','Existencias: 100 unidades por especificación. Impresión exclusiva: 100.000 unidades por diseño.')
const iceSample=t('No digitally printed custom sample. Stock plain or finished samples can be purchased at the quoted price.','不能制作数码打印定制样品；可按报价购买现货白版或成品样品。','No se ofrecen muestras personalizadas de impresión digital. Se pueden comprar muestras existentes sin impresión o terminadas según cotización.')
const iceLead=t('Custom printing: 10–15 days; stock dispatch depends on inventory','专版印刷 10–15 天；现货按库存确认发货','Impresión exclusiva: 10–15 días; despacho de existencias según inventario')
function iceProfile(stocks:string,sourceRows:number[],formats:Text):CommercialProfile{return {sourceRows,stocks,fixedSizes:true,moq:iceMOQ,sample:iceSample,lead:iceLead,dimensions:t('Fixed catalogue sizes only; dimensions below are width × height in cm. Customization is limited to printing.','仅采用现有规格，下表尺寸为宽 × 高，单位 cm；专版只能定制印刷，不可更改尺寸。','Solo medidas existentes; ancho × alto en cm. La personalización se limita a la impresión.'),options:[{name:t('Stock packs','现货冰袋','Acumuladores de existencias'),moq:t('100 pcs per specification','同规格 100 个起','100 unidades por especificación'),scope:formats,sample:iceSample,lead:stockLead},{name:t('Custom multicolour printing','专版多色印刷','Impresión exclusiva a varios colores'),moq:t('100,000 pcs per design','单款 100,000 个','100.000 unidades por diseño'),scope:t('Logos, text, QR codes and artwork on existing sizes. Digital artwork approval before production; no size changes.','在现有规格上印刷 LOGO、文字、二维码或图案，确认电子效果图后生产；不可改尺寸。','Logotipos, texto, códigos QR y diseños sobre medidas existentes. Aprobar el diseño digital antes de producir; sin cambio de medidas.'),sample:iceSample,lead:t('10–15 days','10–15 天','10–15 días')} ]}}
const water=iceProfile('water',[18,19],t('100 / 200 / 400 / 600 ml','100／200／400／600 ml','100 / 200 / 400 / 600 ml'))
const absorbing=iceProfile('absorbing',[20,21],t('100 / 180 / 250 / 400 ml','100／180／250／400 ml','100 / 180 / 250 / 400 ml'))
const segmented=iceProfile('segmented',[22,23],t('1 / 3 / 6 / 12 / 24 cells; cut only along the divisions','单格／3／6／12／24 格，可沿分格裁剪','1 / 3 / 6 / 12 / 24 celdas; recortar solo por las divisiones'))

export const commercialProfiles:Record<string,CommercialProfile>={
 'self-adhesive-foil-bags':adhesive,'open-top-foil-bags':flat,'hand-finished-gusseted-foil-bags':manual,'machine-formed-gusseted-foil-bags':machine,'gusseted-foil-cake-bags':manual,
 'self-seal-non-woven-delivery-bags':nonwoven,'water-fill-ice-packs':water,'self-absorbing-ice-packs':absorbing,'segmented-ice-sheets':segmented,
}
export const commercialProfile=(slug:string)=>commercialProfiles[slug]
export const commercialFAQ=(slug:string)=>{const p=commercialProfile(slug);return p?{q:t('What are the order minimums, sampling terms and lead times?','起订量、打样与交期如何区分？','¿Cuáles son los mínimos, condiciones de muestras y plazos?'),a:t(`${p.moq.en} ${p.sample.en} ${p.lead.en}. Lead times exclude transport; confirm the start date and dispatch schedule with the order.`,`${p.moq.zh} ${p.sample.zh} ${p.lead.zh}。交期不含运输，起算条件和出货日下单时确认。`,`${p.moq.es} ${p.sample.es} ${p.lead.es}. Los plazos excluyen transporte; confirme inicio y despacho al pedir.`)}:undefined}
export type StockSpecification={group:string;dimensions:string;thickness:string;capacity:string;sourceRows:number[];sizeLabel?:Text}
export const stockSpecifications:StockSpecification[]=stockData
export const stockFor=(p:CommercialProfile)=>stockSpecifications.filter(x=>x.group===p.stocks)
