import { yuanenProducts } from './yuanen-catalog'
import { spanish } from './es'
import { extraBags, catalogDetails } from './catalog-data'
export const languages = ['en', 'zh', 'es'] as const
export type Lang = typeof languages[number]
export type Text = Record<Lang, string>
export const locales = {
  en: { tag:'en', og:'en_US', label:'English', short:'EN' },
  zh: { tag:'zh-CN', og:'zh_CN', label:'中文', short:'中文' },
  es: { tag:'es', og:'es_ES', label:'Español', short:'ES' },
} as const
export const tx = (en: string, zh: string, es = spanish[en]): Text => {
  if (!es) throw new Error(`Missing Spanish translation: ${en}`)
  return { en, zh, es }
}
export const brand = { name:'YUANEN', chineseName:'温州远恩工艺品有限公司', email:import.meta.env.VITE_CONTACT_EMAIL||'info@yuanenbag.com', whatsapp:import.meta.env.VITE_WHATSAPP||'+86 189 6971 7999', site:'https://yuanenbag.com', phones:['+86 189 6971 7999','+86 139 6874 4777','+86 136 1665 5488'], verifiedCatalog:true }
export const heroImage = `${import.meta.env.BASE_URL}images/packaging-concept.webp`
export type Bag = {slug:string;name:Text;short:Text;intro:Text;material:Text;use:Text;group:'delivery'|'cold-chain'|'shopping';color:string;type:'box'|'cooler'|'foil'|'ice';considerations:Text[];question:Text;answer:Text;category?:string;styles?:string[];uses?:string[];image?:string;source?:string;gallery?:string[];collection?:'yuanen-2026';catalogPage?:number}
const coreBags:Bag[] = [
 {slug:'zipper-insulated-bags',name:tx('Custom zipper insulated bags','定制拉链保温包'),short:tx('Zipper insulated bags','拉链保温包'),intro:tx('A zip-closure insulated bag for takeaway, grocery and delivery programmes. Specify the outer fabric, insulation, lining and closure together to develop the right construction.','适用于外卖、商超与配送项目的拉链式保温包。外层面料、隔热层、内衬与封口结构应结合使用需求整体确认。'),material:tx('Outer fabric + insulation + lining','外层面料 + 隔热层 + 内衬'),use:tx('Food delivery · Grocery · Takeaway','餐饮配送 · 商超 · 外卖'),group:'delivery',color:'#315345',type:'cooler',considerations:[tx('Measure the usable internal space against your actual food containers or grocery load.','按实际餐盒或商品核对可用内部尺寸。'),tx('Specify zipper type, opening direction, handle length and reinforcement points.','确认拉链类型、开启方向、提手长度及加固位置。'),tx('Agree on thermal testing conditions before specifying retention time.','明确保温时长前，先约定温控测试条件。')],question:tx('How long does a zipper insulated bag keep food cold?','拉链保温包能保冷多久？'),answer:tx('Retention time depends on the insulation, contents, coolant, ambient temperature and opening frequency. Define a test protocol for your intended route; no universal retention time applies to every bag.','保冷时长取决于隔热层、内装物、冰源、环境温度和开启频率，应按实际配送场景约定测试方法，不能给所有袋型统一承诺时长。')},
 {slug:'hook-loop-insulated-bags',name:tx('Custom hook-and-loop insulated bags','定制魔术贴保温包'),short:tx('Hook-and-loop bags','魔术贴保温包'),intro:tx('An insulated bag with a hook-and-loop flap closure, suited to packing workflows where convenient opening and closing matter. Confirm the closure coverage and fit around your contents.','采用魔术贴翻盖封口的保温袋型，便于包装作业中开启与闭合。需结合内装物确认封口覆盖范围及贴合程度。'),material:tx('Outer fabric, insulation, lining and hook-and-loop closure','外层面料、隔热层、内衬及魔术贴'),use:tx('Takeaway · Retail food · Packing','外卖 · 食品零售 · 打包'),group:'delivery',color:'#b79d75',type:'cooler',considerations:[tx('Specify flap overlap, fastening width and closure position.','确认翻盖搭接、魔术贴宽度及位置。'),tx('Check the closed bag with fully loaded containers during sample review.','审样时应装入完整餐盒后检查封口状态。'),tx('Set handling and repeated-opening requirements for the intended use.','根据用途明确搬运及反复开合要求。')],question:tx('Should I choose a zipper or hook-and-loop closure?','应该选择拉链还是魔术贴封口？'),answer:tx('Compare the opening speed, closure coverage, loading method and required thermal performance. Review both samples with your actual containers before choosing; the closure alone does not establish insulation performance.','比较开启效率、封口覆盖、装载方式及保温要求。建议用实际餐盒核对两种样品；仅凭封口方式不能判断整体保温性能。')},
 {slug:'non-woven-bags',name:tx('Custom non-woven tote bags','定制手提无纺布袋'),short:tx('Non-woven tote bags','手提无纺布袋'),intro:tx('Branded non-woven carry bags for takeaway, retail and shopping. Define the fabric weight, gusset, handle construction and artwork around your packaging needs.','适用于外卖、零售与购物的品牌无纺布手提袋。根据包装需求选择面料克重、侧宽、提手结构及印刷方案。'),material:tx('Non-woven fabric; composition and GSM to confirm','无纺布；成分与克重需确认'),use:tx('Retail · Takeaway · Shopping','零售 · 外卖 · 购物'),group:'shopping',color:'#647a64',type:'box',considerations:[tx('GSM is fabric mass per square metre, not a tested load rating.','GSM 表示每平方米面料重量，不等同于经过测试的承重值。'),tx('Confirm sewn or bonded construction and handle reinforcement.','确认车缝或热合结构，以及提手加固方式。'),tx('Check artwork size, print method and colour references before sampling.','打样前核对图稿尺寸、印刷工艺和颜色参考。')],question:tx('Are non-woven bags biodegradable?','无纺布袋可生物降解吗？'),answer:tx('Conventional PP non-woven fabric is a plastic material. Do not describe it as biodegradable or compostable without specific evidence. Confirm the actual material composition and local disposal options.','常规 PP 无纺布是塑料材质，没有特定依据时不应宣称可生物降解或可堆肥。应确认实际材质成分和当地处理方式。')},
 {slug:'foil-insulated-bags',name:tx('Custom foil insulated carry bags','定制手提铝箔保温袋'),short:tx('Foil insulated bags','手提铝箔保温袋'),intro:tx('A foil-faced insulated carry format for food and grocery packaging. Specify the layer structure, finished dimensions and closure to match the intended delivery conditions.','适用于食品与商超包装的铝箔保温手提袋。结合配送条件确认复合层结构、成品尺寸和封口方式。'),material:tx('Foil-faced composite; layer specification to confirm','铝箔复合材料；各层结构需确认'),use:tx('Food packaging · Grocery · Delivery','食品包装 · 商超 · 配送'),group:'delivery',color:'#a1afb0',type:'foil',considerations:[tx('Confirm the composition of every layer rather than relying on a silver appearance.','应确认每一层材料的成分，不能仅凭银色外观判断材质。'),tx('Specify handle type, closure and the dimensions needed around your containers.','确认提手、封口以及容纳餐盒所需的尺寸。'),tx('Request relevant contact-material documentation if direct food contact is intended.','如用于直接接触食品，应索取相关接触材料文件。')],question:tx('Does a silver lining make a bag food-contact compliant?','银色内衬就代表符合食品接触要求吗？'),answer:tx('No. Appearance does not verify compliance. Review the actual contact layer, intended food type, temperature conditions and destination-market requirements with the supplier.','不代表。外观不能证明合规性，应核对实际接触层、食品类型、温度条件及目标市场要求。')},
 {slug:'epe-foam-insulated-bags',name:tx('Custom EPE foam foil insulated bags','定制珍珠棉铝箔保温袋'),short:tx('EPE foam insulated bags','珍珠棉铝箔保温袋'),intro:tx('Insulated packaging combining EPE foam and a foil-faced layer. Define the foam thickness, dimensions and seal construction for the protection and thermal requirements of your shipment.','结合 EPE 珍珠棉和铝箔层的保温包装。根据运输中的防护与温控需求，确认泡棉厚度、尺寸及封口结构。'),material:tx('EPE foam with foil-faced layers','EPE 珍珠棉与铝箔复合层'),use:tx('Fresh food · Cold-chain packing · Delivery','生鲜 · 冷链包装 · 配送'),group:'cold-chain',color:'#c4c7c2',type:'foil',considerations:[tx('Specify foam thickness and density separately; they describe different properties.','厚度与密度是不同参数，需要分别确认。'),tx('Review seam and closure construction alongside the insulating material.','评估隔热材料时，也应检查接缝与封口结构。'),tx('Test the complete packed shipment, including any coolant and outer carton.','应测试包含冰源和外箱在内的完整运输包装。')],question:tx('Is thicker foam always enough to improve delivery performance?','加厚珍珠棉就能保证配送效果吗？'),answer:tx('Thickness is one factor. Contents, coolant quantity, closure, outer packaging, ambient temperature and transit time also matter. Validate the complete packing system under relevant conditions.','厚度只是一个因素。内装物、冰源用量、封口、外包装、环境温度和运输时间同样重要，应在相关条件下验证整套包装。')},
 {slug:'ice-packs',name:tx('Ice packs for insulated packaging','保温包装配套冰袋'),short:tx('Ice packs','冰袋'),intro:tx('Coolant packs for use alongside insulated packaging. Select the pack format, fill specification and quantity for the actual product, route and required temperature range.','用于配套保温包装的蓄冷冰袋。需要根据产品、运输路线及目标温度范围，确认袋型、填充规格与用量。'),material:tx('Pack film and coolant formulation to confirm','袋膜与蓄冷内容物配方需确认'),use:tx('Cold-chain packing · Fresh food · Grocery','冷链包装 · 生鲜 · 商超'),group:'cold-chain',color:'#9cc9d0',type:'ice',considerations:[tx('Confirm pack dimensions, fill weight, seal integrity and handling instructions.','确认尺寸、填充重量、封口完整性及操作说明。'),tx('Plan conditioning and placement to avoid unsuitable direct contact with temperature-sensitive contents.','规划预冷和摆放方式，避免与温度敏感产品不适宜地直接接触。'),tx('Verify performance through shipment testing; do not infer a temperature range from colour or appearance.','通过运输测试确认性能，不依据颜色或外观推测温度范围。')],question:tx('How many ice packs should be used per shipment?','每箱需要配多少冰袋？'),answer:tx('The answer depends on product mass, starting temperature, insulation, transit duration and external conditions. Establish the amount through testing of the complete packed shipment.','用量取决于产品重量、初始温度、隔热包装、运输时长及外部条件，应通过完整运输包装测试确定。')},
]
export const archivedBags:Bag[] = [...coreBags.map(b=>({...b,...catalogDetails[b.slug]})),...extraBags]
export const bags:Bag[] = yuanenProducts
export const steps = [
 {title:tx('Choose your format','选择款式'),body:tx('Select the product family and share your intended use.','选择产品类型，说明实际用途。')},
 {title:tx('Define the details','沟通需求'),body:tx('Confirm size, material, quantity, artwork and delivery requirements.','确认尺寸、材质、数量、图稿和交货要求。')},
 {title:tx('Review the sample','按需定制'),body:tx('Review artwork and samples before approving final specifications.','核对图稿和样品，再确认最终规格。')},
 {title:tx('Plan production','安排生产'),body:tx('Agree on the quotation, quality requirements and production schedule.','确认报价、质量要求和生产排期。')},
 {title:tx('Pack & dispatch','打包发货'),body:tx('Confirm carton packing, inspection requirements and shipping terms.','核对外箱包装、验货要求和运输条款。')},
 {title:tx('Complete & support','交付与售后'),body:tx('Check delivery details and coordinate any after-sales requirements.','确认交付情况，协同处理售后需求。')},
]
export const faq = [
 {q:tx('What does YUANEN manufacture?','远恩主要生产哪些产品？'),a:tx('YUANEN focuses on insulated foil bags, insulated delivery totes, cooler bags and ice packs. We develop the material structure, dimensions and printing around food delivery and cold-chain packing requirements.','远恩专注铝箔保温袋、保温外卖袋、保温包与配套冰袋，围绕餐饮配送和冷链包装需求，确认材料结构、尺寸与印刷方案。','YUANEN se especializa en bolsas térmicas de aluminio, bolsas de reparto, bolsas isotérmicas y acumuladores de frío. Materiales, medidas e impresión se definen para la entrega de alimentos y el embalaje de cadena de frío.')},
 {q:tx('Where is the YUANEN factory network?','远恩生产布局在哪里？'),a:tx('YUANEN is based in Longgang, Wenzhou, with locations in Zhejiang, Shandong and Hunan. The company-confirmed areas are 20,000 m², 5,000 m² and 3,800 m² respectively, totalling 28,800 m².','远恩位于温州龙港，在浙江、山东和湖南设有生产布局。经公司确认的三地面积分别为 20,000㎡、5,000㎡和 3,800㎡，合计 28,800㎡。')},
 {q:tx('What information is needed for a custom bag quote?','定制报价需要哪些信息？'),a:tx('Share the bag type, usable dimensions, layer structure, quantity, artwork, delivery destination and target date. Include testing, compliance and packing requirements so quotations cover the same scope.','请提供袋型、可用尺寸、复合层结构、数量、图稿、交货目的地和目标日期，并说明测试、合规及包装要求，确保报价范围一致。')},
 {q:tx('What are the MOQ and lead time?','起订量和交期是多少？'),a:tx('MOQ and lead time depend on the product, material, artwork and production schedule. Confirm both against your exact specification; the published capacity figure is not a delivery-time commitment for an individual order.','起订量与交期取决于产品、材质、图稿及生产排期，需要按具体规格确认。公布的产能数据不等于对单笔订单交期的承诺。')},
]
export const guides = [
 {slug:'bag-material-comparison',title:tx('Choosing insulation materials','保温包装材料如何选择','Cómo elegir materiales aislantes'),label:tx('MATERIAL COMPARISON','材质对比','COMPARACIÓN DE MATERIALES'),summary:tx('Compare foil composites, EPE, outer fabrics and coolant formats as a complete cold-chain packaging system.','将铝箔复合、EPE、外层面料与冰源作为完整冷链包装系统比较。','Compare laminados de aluminio, EPE, tejidos exteriores y refrigerantes como sistema de embalaje térmico.')},
 {slug:'insulated-bag-materials',title:tx('How to specify an insulated bag','如何确认保温袋材质与结构'),label:tx('MATERIAL GUIDE','材质指南'),summary:tx('Compare outer fabrics, foil layers, EPE foam and closures as one complete packaging system.','将外层面料、铝箔层、EPE 珍珠棉与封口作为完整包装系统比较。')},
 {slug:'custom-bag-order-checklist',title:tx('Your custom bag order checklist','定制袋采购需求清单'),label:tx('BUYING GUIDE','采购指南'),summary:tx('From dimensions to sample approval, prepare the information behind a useful quote.','从尺寸到样品确认，准备有助于获得有效报价的信息。')},
]
export const locations = [{name:tx('Wenzhou, Zhejiang','浙江 · 温州'),area:'20,000',code:'01'},{name:tx('Shandong','山东'),area:'5,000',code:'02'},{name:tx('Hunan','湖南'),area:'3,800',code:'03'}]
