import type { Text } from './data'

const t=(en:string,zh:string,es:string):Text=>({en,zh,es})
export const documentCategories={
 audit:t('Factory audit','工厂审核','Auditoría de fábrica'),
 test:t('Sample testing','样品检测','Ensayos de muestras'),
 material:t('Material certificate','面料认证','Certificación de tejido'),
}
export type QualityDocument={id:string;category:keyof typeof documentCategories;title:Text;number:string;holder:string;issuer:string;date:string;validUntil?:string;pages:number;image:string;result:Text;scope:Text;note:Text}
const charming='Wenzhou Charming Gifts&Crafts Co., Ltd.'
const metalsResult=t('PASS for the listed heavy-metal tests','所列重金属检测项目：PASS','PASS en los ensayos de metales indicados')
const metalsNote=t('Results apply to the submitted bag-body sample. They do not establish full PPWR compliance, food-contact suitability or thermal performance.','结果仅适用于送检袋身样品，不代表整部 PPWR 法规符合性、食品接触适用性或保温性能。','Los resultados corresponden a la muestra del cuerpo de la bolsa. No acreditan cumplimiento íntegro del PPWR, aptitud alimentaria ni rendimiento térmico.')
export const qualityDocuments:QualityDocument[]=[
 {id:'bsci-factory-audit',category:'audit',title:t('amfori BSCI social audit','amfori BSCI 社会责任审核','Auditoría social amfori BSCI'),number:'24-0277774-1',holder:charming,issuer:'Intertek / amfori',date:'2025-09-19',validUntil:'2026-09-29',pages:13,image:'bsci-factory-audit.webp',result:t('Overall rating C','总评级 C','Calificación global C'),scope:t('Follow-up social audit of the named facility at Block 20-B, Huanghe Industrial Park, Longgang.','龙港市黄河产业园 20-B 幢指定工厂的社会责任跟进审核。','Auditoría social de seguimiento de la instalación indicada en el bloque 20-B del parque industrial Huanghe, Longgang.'),note:t('A factory audit record, not product certification. The report includes findings, including a D rating for working hours. Request the full record and current audit status.','此文件属于工厂审核记录，非产品认证；报告包含改进项，工作时间分项评级为 D。完整记录及最新审核状态可咨询确认。','Es un registro de auditoría de fábrica, no una certificación de producto. Incluye hallazgos, con D en jornada laboral. Solicite el informe completo y el estado actual.')},
 {id:'nonwoven-heavy-metals',category:'test',title:t('Non-woven bag · heavy metals','无纺布袋 · 重金属检测','Bolsa no tejida · metales pesados'),number:'CTT2607032795EN',holder:charming,issuer:'Zhejiang Consumer Testing Technology Co., Ltd. (CTT)',date:'2026-07-21',pages:3,image:'nonwoven-heavy-metals.webp',result:metalsResult,scope:t('Red non-woven bag body with white printing. Pb, Cd, Hg and Cr(VI) content under the report’s (EU) 2025/40 test scope.','红色无纺布、白色印刷的袋身样品；报告按 (EU) 2025/40 所列范围检测铅、镉、汞与六价铬含量。','Cuerpo de bolsa no tejida roja con impresión blanca. Contenido de Pb, Cd, Hg y Cr(VI) según el alcance del informe referido al Reglamento (UE) 2025/40.'),note:metalsNote},
 {id:'polyester-heavy-metals',category:'test',title:t('Polyester bag · heavy metals','聚酯袋 · 重金属检测','Bolsa de poliéster · metales pesados'),number:'CTT2607032794EN',holder:charming,issuer:'Zhejiang Consumer Testing Technology Co., Ltd. (CTT)',date:'2026-07-21',pages:3,image:'polyester-heavy-metals.webp',result:metalsResult,scope:t('White synthetic-fibre bag body with multicolour printing. Pb, Cd, Hg and Cr(VI) content under the report’s (EU) 2025/40 test scope.','白色合成纤维、多色印刷的聚酯袋身样品；报告按 (EU) 2025/40 所列范围检测铅、镉、汞与六价铬含量。','Cuerpo de bolsa de fibra sintética blanca con impresión multicolor. Contenido de Pb, Cd, Hg y Cr(VI) según el alcance del informe referido al Reglamento (UE) 2025/40.'),note:metalsNote},
 {id:'rpet-heavy-metals',category:'test',title:t('RPET bag · heavy metals','RPET 袋 · 重金属检测','Bolsa RPET · metales pesados'),number:'CTT2607032793EN',holder:charming,issuer:'Zhejiang Consumer Testing Technology Co., Ltd. (CTT)',date:'2026-07-21',pages:3,image:'rpet-heavy-metals.webp',result:metalsResult,scope:t('Bag-body sample with brown/dark-brown printing and transparent plastic. Pb, Cd, Hg and Cr(VI) content under the report’s (EU) 2025/40 test scope.','棕色／深棕色印刷及透明塑料的袋身样品；报告按 (EU) 2025/40 所列范围检测铅、镉、汞与六价铬含量。','Muestra de cuerpo de bolsa con impresión marrón/marrón oscuro y plástico transparente. Contenido de Pb, Cd, Hg y Cr(VI) según el alcance del informe referido al Reglamento (UE) 2025/40.'),note:t('This report tests the listed heavy metals. It does not verify recycled content and is not a GRS or RCS certificate. Results apply to the submitted sample.','本报告仅检测所列重金属，不验证再生成分比例，也不是 GRS 或 RCS 证书；结果适用于送检样品。','El informe analiza los metales indicados. No verifica contenido reciclado ni es un certificado GRS o RCS. Los resultados se limitan a la muestra presentada.')},
 {id:'cotton-linen-lead',category:'test',title:t('Cotton-linen bag · lead content','棉麻袋 · 铅含量检测','Bolsa de algodón-lino · contenido de plomo'),number:'CTT2607061300EN',holder:charming,issuer:'Fujian Consumer Testing Technology Co., Ltd. (CTT)',date:'2026-07-25',pages:3,image:'cotton-linen-lead.webp',result:t('PASS for lead content','铅含量检测：PASS','PASS para contenido de plomo'),scope:t('Brown bag-body fabric with black printing; CPSIA Section 101 and 15 U.S.C. §1278a lead content. Method CPSC-CH-E1002-08.3.','棕色面料、黑色印刷的袋身样品；CPSIA 第 101 节及 15 U.S.C. §1278a 的铅含量项目，方法为 CPSC-CH-E1002-08.3。','Tejido marrón del cuerpo de la bolsa con impresión negra; contenido de plomo según CPSIA, sección 101, y 15 U.S.C. §1278a. Método CPSC-CH-E1002-08.3.'),note:t('Limited to the lead test and submitted sample. This is not certification of all CPSIA requirements or of an insulated finished product.','仅限送检样品的铅含量项目，不代表全部 CPSIA 要求或保温成品获得认证。','Limitado al ensayo de plomo y a la muestra presentada. No certifica todos los requisitos CPSIA ni un producto térmico terminado.')},
 {id:'oeko-tex-cotton-fabric',category:'material',title:t('OEKO-TEX STANDARD 100 · cotton fabric','OEKO-TEX STANDARD 100 · 全棉面料','OEKO-TEX STANDARD 100 · tejido de algodón'),number:'25.HCN.43344',holder:'SHAOXING KEQIAO QIANQUAN TEXTILE CO., LTD.',issuer:'Hohenstein Laboratories GmbH & Co. KG',date:'2026-07-21',validUntil:'2027-06-30',pages:1,image:'oeko-tex-cotton-fabric.webp',result:t('Product class I · Annex 4','产品级别 I · 附录 4','Clase de producto I · Anexo 4'),scope:t('Raw-white, bleached, reactive-dyed and reactive-printed woven cotton fabrics within the named holder’s certificate scope.','持证方认证范围内的本白、漂白、活性染色及活性印花全棉梭织面料。','Tejidos de algodón de calada en crudo blanco, blanqueados, teñidos y estampados con reactivos dentro del alcance del titular.'),note:t('Certification covers the specified fabric. It does not certify every finished bag, foil lining, ice pack or other material supplied by YUANEN.','认证覆盖指定面料，不覆盖远恩提供的所有成品袋、铝箔内层、冰袋或其他材料。','La certificación cubre el tejido especificado. No certifica todas las bolsas terminadas, forros de aluminio, acumuladores de frío u otros materiales de YUANEN.')},
]
export const qualityImage=(file:string)=>`${import.meta.env.BASE_URL}images/documents/${file}`
