// Spanish translations shared by page content, metadata and enquiry briefs.
export const spanish: Record<string, string> = {
  "product family": "familia de productos",
  "YUANEN home": "Inicio de YUANEN",
  "INSULATED PACKAGING": "EMBALAJE TÉRMICO",
  "Products": "Productos",
  "Applications": "Aplicaciones",
  "Customization": "Personalización",
  "Our factory": "Nuestra fábrica",
  "Resources": "Recursos",
  "INSULATED PACKAGING · MADE IN CHINA": "EMBALAJE TÉRMICO · FABRICADO EN CHINA",
  "WENZHOU · SHANDONG · HUNAN": "WENZHOU · SHANDONG · HUNAN",
  "Main navigation": "Navegación principal",
  "Request a quote": "Solicitar presupuesto",
  "切换为中文": "Cambiar a chino",
  "Packaging that carries your brand.\nExpertise that carries your business.": "Embalajes que representan su marca.\nExperiencia que respalda su negocio.",
  "EXPLORE": "CONOZCA YUANEN",
  "Product families": "Familias de productos",
  "Factory & capabilities": "Fábrica y capacidad de producción",
  "RESOURCES": "RECURSOS",
  "Prepare an enquiry": "Preparar una consulta",
  "FIND US": "CONTACTO",
  "Longgang, Wenzhou · China": "Longgang, Wenzhou · China",
  "Let’s talk packaging": "Hablemos de su embalaje",
  "All rights reserved.": "Todos los derechos reservados.",
  "Privacy": "Privacidad",
  "Thoughtfully made. Carefully delivered.": "Fabricación cuidadosa. Entrega responsable.",
  "Breadcrumb": "Ruta de navegación",
  "Home": "Inicio",
  "Years of packaging experience": "Años de experiencia en embalaje",
  "Across three locations": "En tres centros de producción",
  "3M": "3 M",
  "Pieces daily capacity¹": "Unidades de capacidad diaria¹",
  "¹ Company-confirmed capacity. Actual output and lead time depend on product specifications and the production schedule.": "¹ Capacidad confirmada por la empresa. La producción real y el plazo de entrega dependen de las especificaciones y de la planificación de producción.",
  "FORMAT ILLUSTRATION": "ILUSTRACIÓN DEL FORMATO",
  "YOUR BRAND. YOUR SPECIFICATION.": "SU MARCA. SUS ESPECIFICACIONES.",
  "Discuss Your Packaging Requirements": "Cuéntenos qué embalaje necesita",
  "Tell us about your project": "Háblenos de su proyecto",
  "Read the guide": "Leer la guía",
  "YUANEN · INSULATED PACKAGING": "YUANEN · EMBALAJE TÉRMICO",
  "Insulated Bag": "Bolsas térmicas",
  "Manufacturer": "Fabricación a medida",
  "Custom insulated bags, non-woven packaging and ice packs for food delivery, grocery and cold-chain applications. Three production locations in China. Built to your specifications.": "Bolsas térmicas, embalajes de tejido no tejido y bolsas refrigerantes a medida para reparto de comida, supermercados y cadena de frío. Tres centros de producción en China. Fabricación según sus especificaciones.",
  "View product range": "Ver productos",
  "Meet the factory": "Conocer la fábrica",
  "Longgang, Wenzhou · Serving brands near and far": "Longgang, Wenzhou · Al servicio de marcas de todo el mundo",
  "INSIDE YUANEN": "DENTRO DE YUANEN",
  "From material to finished bag.": "De la materia prima a la bolsa terminada.",
  "Explore the factory": "Visitar la fábrica",
  "REAL FACTORY. REAL CAPABILITY.": "FÁBRICA REAL. CAPACIDAD DEMOSTRABLE.",
  "PRODUCT CATEGORIES": "CATEGORÍAS DE PRODUCTOS",
  "Insulated Bags & Packaging Products": "Bolsas térmicas y soluciones de embalaje",
  "Compare six product families by material, construction and application.": "Compare seis familias de productos por material, estructura y aplicación.",
  "All products": "Todos los productos",
  "Illustrations show bag formats. Materials, dimensions, printing and performance are confirmed for each order.": "Las ilustraciones muestran los formatos. Los materiales, las dimensiones, la impresión y el rendimiento se confirman para cada pedido.",
  "YUANEN · WENZHOU, CHINA": "YUANEN · WENZHOU, CHINA",
  "MANUFACTURING CAPABILITIES": "CAPACIDAD DE FABRICACIÓN",
  "Three Locations.\n28,800 m² of Facilities.": "Tres centros.\n28.800 m² de instalaciones.",
  "Based in Longgang, Wenzhou, YUANEN brings together packaging design, development, manufacturing and after-sales experience. Our footprint spans Zhejiang, Shandong and Hunan.": "Con sede en Longgang, Wenzhou, YUANEN reúne experiencia en diseño, desarrollo, fabricación y servicio posventa de embalajes. Nuestra red abarca Zhejiang, Shandong y Hunan.",
  "Go inside our factory": "Conozca nuestras instalaciones",
  "BRANDS WE HAVE SERVED": "MARCAS A LAS QUE HEMOS PRESTADO SERVICIO",
  "Yonghui": "Yonghui",
  "Haidilao": "Haidilao",
  "CUSTOM MANUFACTURING": "FABRICACIÓN A MEDIDA",
  "From Specification to Delivery": "De las especificaciones a la entrega",
  "Explore customization": "Ver el proceso de personalización",
  "TECHNICAL & PURCHASING RESOURCES": "RECURSOS TÉCNICOS Y DE COMPRA",
  "Packaging Materials & Buying Guides": "Materiales de embalaje y guías de compra",
  "Practical guidance to make your next sourcing conversation more productive.": "Orientación práctica para preparar mejor su próxima consulta de compra.",
  "FREQUENTLY ASKED QUESTIONS": "PREGUNTAS FRECUENTES",
  "Manufacturer & Product FAQ": "Preguntas sobre la fábrica y los productos",
  "Clear specifications are the foundation of a successful packaging project.": "Unas especificaciones claras son la base de un proyecto de embalaje bien definido.",
  "Food delivery": "Reparto de comida",
  "Cold-chain packaging": "Cadena de frío",
  "Retail & shopping": "Comercio y compras",
  "PACKAGING WITH A PURPOSE": "EMBALAJE PARA CADA NECESIDAD",
  "Insulated Packaging Products": "Productos de embalaje térmico",
  "Insulated bags, non-woven packaging and coolant packs. Explore our product families, then make the specification your own.": "Bolsas térmicas, embalajes de tejido no tejido y bolsas refrigerantes. Explore nuestras familias de productos y defina las especificaciones de su proyecto.",
  "Filter by use": "Filtrar por aplicación",
  "Search products": "Buscar productos",
  "product families": "familias de productos",
  "No matching products": "No se encontraron productos",
  "Try another material or reset your filters.": "Pruebe otro material o restablezca los filtros.",
  "Reset filters": "Restablecer filtros",
  "Format illustrations are design references. Ask for current product photographs and samples when confirming your specification.": "Las ilustraciones de formatos son referencias de diseño. Solicite fotografías y muestras actuales al confirmar sus especificaciones.",
  "Product family": "Familia de productos",
  "Material structure": "Estructura del material",
  "Typical applications": "Aplicaciones habituales",
  "Dimensions & quantity": "Dimensiones y cantidad",
  "Defined in your project brief": "Según los requisitos de su proyecto",
  "Printing & branding": "Impresión y marca",
  "Artwork and process to be confirmed": "Diseño y proceso por confirmar",
  "MOQ, price & lead time": "Pedido mínimo, precio y plazo",
  "Quoted against confirmed specifications": "Presupuesto según las especificaciones confirmadas",
  "CONSTRUCTION ILLUSTRATION · NOT TO SCALE": "ILUSTRACIÓN DE LA ESTRUCTURA · SIN ESCALA",
  "YUANEN / CUSTOM PACKAGING": "YUANEN / EMBALAJE A MEDIDA",
  "Enquire about this product": "Consultar sobre este producto",
  "SPECIFY IT WELL": "DEFINA LAS ESPECIFICACIONES",
  "What to confirm before production": "Qué confirmar antes de producir",
  "BUYER’S QUESTION": "PREGUNTA DEL COMPRADOR",
  "A useful answer.": "Una respuesta práctica.",
  "ALSO EXPLORE": "DESCUBRA TAMBIÉN",
  "Complete your packaging system.": "Complete su sistema de embalaje.",
  "Factory photograph": "Fotografía de la fábrica",
  "Close image": "Cerrar imagen",
  "BUILT ON REAL CAPABILITY": "CAPACIDAD DE FABRICACIÓN REAL",
  "YUANEN Manufacturing Facilities": "Instalaciones de producción de YUANEN",
  "A packaging partner rooted in Longgang, Wenzhou. Ten years of experience. Three locations. One focus: your packaging.": "Un socio de embalaje con sede en Longgang, Wenzhou. Diez años de experiencia. Tres centros. Un objetivo: su embalaje.",
  "Where your packaging takes shape.": "Donde su embalaje toma forma.",
  "OUR STORY": "NUESTRA EMPRESA",
  "From Longgang.\nFor brands everywhere.": "Desde Longgang.\nPara marcas de todo el mundo.",
  "YUANEN is based in Longgang, Wenzhou, a centre for printing and non-woven manufacturing, close to established woven-plastics and bag-making supply chains.": "YUANEN tiene su sede en Longgang, Wenzhou, un centro de impresión y fabricación de tejidos no tejidos, próximo a cadenas de suministro consolidadas de plástico tejido y fabricación de bolsas.",
  "We focus on zipper and hook-and-loop insulated bags, non-woven carry bags, foil insulated packaging, EPE foam foil bags and ice packs. Our experience covers packaging design, development, production, sales and after-sales coordination.": "Nos especializamos en bolsas térmicas con cremallera y cierre de gancho y bucle, bolsas de tejido no tejido, embalajes térmicos con aluminio, bolsas de espuma EPE con aluminio y bolsas refrigerantes. Nuestra experiencia abarca diseño, desarrollo, producción, ventas y coordinación posventa.",
  "REGISTERED CHINESE COMPANY NAME": "RAZÓN SOCIAL REGISTRADA EN CHINO",
  "THE WORK BEHIND THE PRODUCT": "EL TRABAJO DETRÁS DEL PRODUCTO",
  "Production, Materials & Warehousing": "Producción, materiales y almacenamiento",
  "Production, materials, assembly and storage — photographs from YUANEN’s company materials.": "Producción, materiales, confección y almacenamiento: fotografías de los materiales corporativos de YUANEN.",
  "ONE NETWORK. THREE LOCATIONS.": "UNA RED. TRES CENTROS.",
  "Closer to the supply chain.": "Cerca de la cadena de suministro.",
  "Our manufacturing footprint spans Zhejiang, Shandong and Hunan.": "Nuestra red de producción abarca Zhejiang, Shandong y Hunan.",
  "Areas and capacity follow the current company materials confirmed on 18 September 2026.": "Las superficies y la capacidad corresponden a los materiales corporativos vigentes, confirmados el 18 de septiembre de 2026.",
  "MORE THAN MANUFACTURING": "MÁS ALLÁ DE LA FABRICACIÓN",
  "A clear process.\nA considered partnership.": "Un proceso claro.\nUna colaboración bien definida.",
  "Custom specifications": "Especificaciones a medida",
  "Start with your size, material, print and packing requirements.": "Partimos de sus requisitos de dimensiones, materiales, impresión y embalaje.",
  "Production & dispatch planning": "Planificación de producción y expedición",
  "Confirm capacity, inspection and delivery arrangements for your order.": "Confirmamos la capacidad disponible, la inspección y la entrega para su pedido.",
  "After-sales coordination": "Coordinación posventa",
  "Keep product requirements and delivery details clear throughout the project.": "Mantenemos claros los requisitos del producto y los detalles de entrega durante todo el proyecto.",
  "MADE FOR YOUR SPECIFICATION": "FABRICADO SEGÚN SUS ESPECIFICACIONES",
  "Good packaging starts\nwith a clear brief.": "Un buen embalaje empieza\ncon requisitos claros.",
  "Size, materials, insulation, print and finish. Bring the details together before production starts.": "Dimensiones, materiales, aislamiento, impresión y acabado. Defina los detalles antes de iniciar la producción.",
  "THE DETAILS MAKE THE DIFFERENCE": "LOS DETALLES MARCAN LA DIFERENCIA",
  "Make every layer work.": "Cada capa cumple su función.",
  "An insulated bag works as a complete structure. Define the outer layer, insulation, lining, seams and closure together. Use sample approval to align the specification before ordering.": "Una bolsa térmica funciona como una estructura completa. Defina conjuntamente la capa exterior, el aislamiento, el revestimiento, las costuras y el cierre. Revise la muestra para acordar las especificaciones antes de realizar el pedido.",
  "Dimensions based on your actual contents": "Dimensiones según el contenido real",
  "Material composition and thickness": "Composición y espesor de los materiales",
  "Artwork, print area and colour references": "Diseño, área de impresión y referencias de color",
  "Handles, closures and reinforcement": "Asas, cierres y refuerzos",
  "Packing, testing and delivery requirements": "Requisitos de embalaje, ensayo y entrega",
  "Read the order checklist": "Leer la lista de requisitos del pedido",
  "KNOW YOUR PACKAGING": "CONOZCA SU EMBALAJE",
  "Technical & Purchasing Resources": "Recursos técnicos y de compra",
  "Practical material and purchasing guides for your next insulated packaging project.": "Guías prácticas de materiales y compra para su próximo proyecto de embalaje térmico.",
  "Outer fabric": "Tejido exterior",
  "Non-woven or other specified fabric": "Tejido no tejido u otro tejido especificado",
  "Composition, fabric weight, colour, print method and handle reinforcement": "Composición, gramaje, color, método de impresión y refuerzo de asas",
  "Insulation layer": "Capa aislante",
  "EPE foam or specified composite": "Espuma EPE o material compuesto especificado",
  "Thickness, density, coverage and construction": "Espesor, densidad, cobertura y estructura",
  "Inner surface": "Superficie interior",
  "Foil-faced or other specified lining": "Revestimiento con aluminio u otro material especificado",
  "Exact contact material, seams and relevant compliance documents": "Material exacto de contacto, costuras y documentación de conformidad pertinente",
  "Closure": "Cierre",
  "Zipper, hook-and-loop or agreed seal": "Cremallera, gancho y bucle o sellado acordado",
  "Opening method, overlap and repeated-use requirements": "Método de apertura, solapamiento y requisitos de uso repetido",
  "Coolant": "Refrigerante",
  "Ice packs as specified": "Bolsas refrigerantes según especificación",
  "Conditioning, fill weight, quantity and position in the pack-out": "Acondicionamiento, peso de llenado, cantidad y posición en el embalaje",
  "Contents": "Contenido",
  "Product and container dimensions": "Dimensiones del producto y del recipiente",
  "Measure usable internal space, including coolant and any protective layers": "Mida el espacio interior útil, incluido el refrigerante y las capas de protección",
  "Order scope": "Alcance del pedido",
  "Quantity, variations and artwork": "Cantidad, variantes y diseño de impresión",
  "Separate sample approval from bulk production approval": "Separe la aprobación de la muestra de la autorización de producción en serie",
  "Performance": "Rendimiento",
  "Temperature, time and handling": "Temperatura, tiempo y manipulación",
  "Specify the route and conditions, not only a desired number of hours": "Especifique la ruta y las condiciones, no solo el número de horas deseado",
  "Delivery": "Entrega",
  "Destination and target date": "Destino y fecha prevista",
  "Confirm whether lead time includes sampling, manufacture and transport": "Confirme si el plazo incluye muestras, fabricación y transporte",
  "Quotation": "Presupuesto",
  "Unit price and total cost": "Precio unitario y coste total",
  "Check artwork setup, sampling, packing, freight and delivery terms": "Revise la preparación de impresión, las muestras, el embalaje, el transporte y las condiciones de entrega",
  "Insights": "Guías de compra",
  "Updated 18 September 2026 · Buyer reference": "Actualizado el 18 de septiembre de 2026 · Referencia para compradores",
  "THE DIRECT ANSWER": "RESPUESTA DIRECTA",
  "Specify an insulated bag as a complete system: outer fabric, insulation, lining, closure, contents and coolant. A material name or a single thickness does not establish the thermal performance of the finished shipment.": "Defina la bolsa térmica como un sistema completo: tejido exterior, aislamiento, revestimiento, cierre, contenido y refrigerante. El nombre de un material o un único espesor no determinan el rendimiento térmico del envío terminado.",
  "A useful custom bag quotation starts with a defined product, size, material, quantity and destination. Add artwork, required performance, packing and target dates so suppliers can quote the same specification.": "Un presupuesto útil para bolsas a medida empieza por definir el producto, las dimensiones, el material, la cantidad y el destino. Añada el diseño, el rendimiento requerido, el embalaje y las fechas previstas para que los proveedores presupuesten las mismas especificaciones.",
  "What to compare": "Qué comparar",
  "Component": "Componente",
  "Specify": "Qué especificar",
  "Confirm before ordering": "Qué confirmar antes del pedido",
  "Match the test to the delivery route": "Adapte el ensayo a la ruta de entrega",
  "Review the sample against a written specification": "Revise la muestra con unas especificaciones por escrito",
  "Record the initial product temperature, packed mass, coolant preparation, ambient profile, transit time and frequency of opening. Define where temperature is measured and the acceptable range. Evaluate the complete pack-out with the outer carton or delivery container that will actually be used.": "Registre la temperatura inicial del producto, la masa embalada, la preparación del refrigerante, el perfil de temperatura ambiente, el tiempo de transporte y la frecuencia de apertura. Defina los puntos de medición y el intervalo aceptable. Evalúe el embalaje completo con la caja exterior o el recipiente de reparto que se utilizará realmente.",
  "Check dimensions, material layers, printing, handles, closure, seams and packing. Record revisions and keep the approved sample and specification aligned. Any performance or compliance requirement should have a corresponding acceptance method.": "Compruebe dimensiones, capas de material, impresión, asas, cierre, costuras y embalaje. Registre los cambios y mantenga la muestra aprobada y las especificaciones alineadas. Todo requisito de rendimiento o conformidad debe tener un método de aceptación correspondiente.",
  "Avoid assumptions that change the outcome": "Evite suposiciones que alteren el resultado",
  "A silver appearance does not establish material composition or food-contact compliance.": "El aspecto plateado no demuestra la composición del material ni su conformidad para contacto alimentario.",
  "Published factory capacity is not an individual order lead-time guarantee.": "La capacidad publicada de la fábrica no garantiza el plazo de entrega de un pedido concreto.",
  "Thermal performance needs relevant test evidence; do not transfer another product’s rating.": "El rendimiento térmico requiere ensayos pertinentes; no aplique a un producto la clasificación de otro.",
  "This is a purchasing reference, not a product test report or regulatory certification. Confirm the final construction and requirements for your destination market.": "Esta guía es una referencia de compra, no un informe de ensayo ni una certificación reglamentaria. Confirme la estructura final y los requisitos del mercado de destino.",
  "Related product families": "Familias de productos relacionadas",
  "Prepare your project brief": "Prepare los requisitos de su proyecto",
  "Food delivery & takeaway": "Reparto de comida y comida para llevar",
  "Start with your container dimensions, packing speed, delivery route and opening frequency. Compare zipper, hook-and-loop and foil formats around the way your team packs orders.": "Parta de las dimensiones de los recipientes, la velocidad de preparación, la ruta de reparto y la frecuencia de apertura. Compare formatos con cremallera, gancho y bucle o aluminio según la forma de preparar pedidos de su equipo.",
  "Container fit · Closure · Handles · Branding": "Ajuste del recipiente · Cierre · Asas · Marca",
  "Grocery & retail": "Supermercados y comercio minorista",
  "Coordinate branded carry bags with the size and handling needs of the products you sell. For temperature-sensitive goods, specify an appropriate insulation and coolant arrangement separately.": "Adapte las bolsas con su marca a las dimensiones y necesidades de manipulación de sus productos. Para productos sensibles a la temperatura, especifique por separado el aislamiento y la disposición del refrigerante.",
  "Load requirements · Dimensions · Print area · Packing": "Carga prevista · Dimensiones · Área de impresión · Embalaje",
  "Fresh food & cold-chain packing": "Alimentos frescos y cadena de frío",
  "Consider the insulated bag, ice packs and outer packaging as one pack-out. Define the target temperature range and transit conditions, then validate performance before scale-up.": "Considere la bolsa térmica, las bolsas refrigerantes y el embalaje exterior como un conjunto. Defina el intervalo de temperatura y las condiciones de transporte; después, valide el rendimiento antes de ampliar su uso.",
  "Transit profile · EPE structure · Coolant · Test conditions": "Perfil de transporte · Estructura EPE · Refrigerante · Condiciones de ensayo",
  "BUILT AROUND THE JOURNEY": "DISEÑADO PARA CADA TRAYECTO",
  "Packaging by Application": "Embalaje por aplicación",
  "Define the application first. Choose the packaging around real handling and delivery conditions.": "Defina primero la aplicación. Elija el embalaje según las condiciones reales de manipulación y entrega.",
  "Privacy & your enquiry.": "Privacidad y consultas.",
  "Updated 18 September 2026": "Actualizado el 18 de septiembre de 2026",
  "Your project details": "Los datos de su proyecto",
  "The enquiry form prepares a brief in your browser. Your name, email and project details stay in the current page until you choose to download the brief or open an email app. This website does not automatically send or store enquiry details on a server.": "El formulario prepara un documento de requisitos en su navegador. Su nombre, correo electrónico y datos del proyecto permanecen en la página actual hasta que decida descargar el documento o abrir su aplicación de correo. Este sitio no envía ni almacena automáticamente los datos de consulta en un servidor.",
  "Downloads and email": "Descargas y correo electrónico",
  "Downloading saves a text file on your device. If an email address is configured, the email link opens your own email app with a draft. Review the recipient and content there before sending. The email provider’s terms apply to any message you send.": "La descarga guarda un archivo de texto en su dispositivo. Si hay una dirección de contacto configurada, el enlace de correo abre un borrador en su aplicación de correo. Revise allí el destinatario y el contenido antes de enviarlo. Los mensajes que envíe están sujetos a las condiciones de su proveedor de correo.",
  "Website operation": "Funcionamiento del sitio",
  "This version has no advertising trackers or third-party analytics scripts. Hosting providers may process basic request information such as IP address and request time to operate the website. External links follow the destination website’s policies.": "Esta versión no incluye rastreadores publicitarios ni herramientas de analítica de terceros. El proveedor de alojamiento puede tratar datos básicos de las solicitudes, como la dirección IP y la hora, para operar el sitio. Los enlaces externos están sujetos a las políticas del sitio de destino.",
  "Contact": "Contacto",
  "Longgang, Wenzhou, China": "Longgang, Wenzhou, China",
  "A public email contact will be added when confirmed.": "Se añadirá un correo de contacto público cuando esté confirmado.",
  "Enquiry": "Consulta",
  "This page has moved out of the bag.": "No se ha encontrado esta página.",
  "Back to home": "Volver al inicio",
  "Skip to content": "Saltar al contenido",
  "Name": "Nombre",
  "Email": "Correo electrónico",
  "Company": "Empresa",
  "Bag format": "Formato de bolsa",
  "Quantity": "Cantidad",
  "Dimensions (W × H × D, cm)": "Dimensiones (ancho × alto × fondo, cm)",
  "Destination": "Destino",
  "Project details": "Detalles del proyecto",
  "To discuss": "Por definir",
  "CUSTOM BAG ENQUIRY": "CONSULTA DE BOLSAS A MEDIDA",
  "Draft only. This file has not been sent. Final specifications, pricing and availability require confirmation.": "Solo es un borrador. Este archivo no se ha enviado. Las especificaciones finales, los precios y la disponibilidad requieren confirmación.",
  "YOUR PACKAGING REQUIREMENTS": "SUS REQUISITOS DE EMBALAJE",
  "Request a Custom Packaging Quote": "Solicite un presupuesto de embalaje a medida",
  "A few details now. A clearer conversation about your packaging next.": "Comparta algunos detalles para que podamos hablar de su embalaje con mayor precisión.",
  "BASED IN": "UBICACIÓN",
  "Wenzhou, China": "Wenzhou, China",
  "COMPANY": "EMPRESA",
  "Prefer to get your details ready first? Prepare and download your brief below.": "¿Prefiere preparar primero los datos? Complete el formulario para generar y descargar sus requisitos.",
  "YOUR DETAILS": "SUS DATOS",
  "* Required": "* Obligatorio",
  "Your name *": "Su nombre *",
  "Work email *": "Correo de trabajo *",
  "YOUR PROJECT": "SU PROYECTO",
  "Bag format *": "Formato de bolsa *",
  "Select a bag format": "Seleccione un formato",
  "Other / help me choose": "Otro / Necesito asesoramiento",
  "Estimated quantity (pieces) *": "Cantidad estimada (unidades) *",
  "Width × height × depth (cm)": "Ancho × alto × fondo (cm)",
  "Delivery country / region *": "País o región de entrega *",
  "Tell us about your project *": "Háblenos de su proyecto *",
  "Materials, printing, intended use, target delivery date and any testing requirements…": "Materiales, impresión, uso previsto, fecha de entrega y requisitos de ensayo…",
  "I have read the ": "He leído la ",
  "privacy information": "información de privacidad",
  " and understand this step prepares a draft.": " y entiendo que este paso prepara un borrador.",
  "Prepare my enquiry": "Preparar mi consulta",
  "Review your brief before opening your email app. Nothing is sent automatically.": "Revise los requisitos antes de abrir su aplicación de correo. No se envía nada automáticamente.",
  "Downloadable enquiry brief. Online delivery is not available yet; your details stay in this page.": "Documento de consulta descargable. El envío en línea aún no está disponible; sus datos permanecen en esta página.",
  "Close": "Cerrar",
  "Your brief is ready.": "Su documento está listo.",
  "Review and save your draft. It has not been sent.": "Revise y guarde el borrador. Todavía no se ha enviado.",
  "Enquiry draft": "Borrador de la consulta",
  "Download brief": "Descargar documento",
  "Open email app": "Abrir aplicación de correo",
  "Custom zipper insulated bags": "Bolsas térmicas con cremallera a medida",
  "Zipper insulated bags": "Bolsas térmicas con cremallera",
  "A zip-closure insulated bag for takeaway, grocery and delivery programmes. Specify the outer fabric, insulation, lining and closure together to develop the right construction.": "Bolsa térmica con cremallera para comida para llevar, supermercados y programas de reparto. Especifique conjuntamente el tejido exterior, el aislamiento, el revestimiento y el cierre para definir la estructura adecuada.",
  "Outer fabric + insulation + lining": "Tejido exterior + aislamiento + revestimiento",
  "Food delivery · Grocery · Takeaway": "Reparto de comida · Supermercados · Comida para llevar",
  "Measure the usable internal space against your actual food containers or grocery load.": "Compruebe el espacio interior útil con los recipientes de comida o la carga de productos reales.",
  "Specify zipper type, opening direction, handle length and reinforcement points.": "Especifique el tipo de cremallera, la dirección de apertura, la longitud de las asas y los puntos de refuerzo.",
  "Agree on thermal testing conditions before specifying retention time.": "Acuerde las condiciones del ensayo térmico antes de indicar un tiempo de conservación.",
  "How long does a zipper insulated bag keep food cold?": "¿Cuánto tiempo mantiene fríos los alimentos una bolsa térmica con cremallera?",
  "Retention time depends on the insulation, contents, coolant, ambient temperature and opening frequency. Define a test protocol for your intended route; no universal retention time applies to every bag.": "El tiempo de conservación depende del aislamiento, el contenido, el refrigerante, la temperatura ambiente y la frecuencia de apertura. Defina un protocolo de ensayo para su ruta; no existe un tiempo universal aplicable a todas las bolsas.",
  "Custom hook-and-loop insulated bags": "Bolsas térmicas con cierre de gancho y bucle a medida",
  "Hook-and-loop bags": "Bolsas con cierre de gancho y bucle",
  "An insulated bag with a hook-and-loop flap closure, suited to packing workflows where convenient opening and closing matter. Confirm the closure coverage and fit around your contents.": "Bolsa térmica con solapa y cierre de gancho y bucle, adecuada para procesos que requieren una apertura y un cierre cómodos. Confirme la cobertura del cierre y el ajuste al contenido.",
  "Outer fabric, insulation, lining and hook-and-loop closure": "Tejido exterior, aislamiento, revestimiento y cierre de gancho y bucle",
  "Takeaway · Retail food · Packing": "Comida para llevar · Comercio alimentario · Preparación de pedidos",
  "Specify flap overlap, fastening width and closure position.": "Especifique el solapamiento de la solapa, el ancho del cierre y su posición.",
  "Check the closed bag with fully loaded containers during sample review.": "Al revisar la muestra, compruebe la bolsa cerrada con los recipientes completamente cargados.",
  "Set handling and repeated-opening requirements for the intended use.": "Defina los requisitos de manipulación y apertura repetida según el uso previsto.",
  "Should I choose a zipper or hook-and-loop closure?": "¿Conviene elegir cremallera o cierre de gancho y bucle?",
  "Compare the opening speed, closure coverage, loading method and required thermal performance. Review both samples with your actual containers before choosing; the closure alone does not establish insulation performance.": "Compare la velocidad de apertura, la cobertura del cierre, el método de carga y el rendimiento térmico requerido. Revise ambos formatos con sus recipientes reales antes de elegir; el cierre por sí solo no determina el aislamiento.",
  "Custom non-woven tote bags": "Bolsas de tejido no tejido a medida",
  "Non-woven tote bags": "Bolsas de tejido no tejido",
  "Branded non-woven carry bags for takeaway, retail and shopping. Define the fabric weight, gusset, handle construction and artwork around your packaging needs.": "Bolsas de tejido no tejido con su marca para comida para llevar, comercio y compras. Defina el gramaje, el fuelle, las asas y el diseño según sus necesidades de embalaje.",
  "Non-woven fabric; composition and GSM to confirm": "Tejido no tejido; composición y gramaje por confirmar",
  "Retail · Takeaway · Shopping": "Comercio · Comida para llevar · Compras",
  "GSM is fabric mass per square metre, not a tested load rating.": "El gramaje en g/m² indica la masa del tejido por metro cuadrado, no una capacidad de carga ensayada.",
  "Confirm sewn or bonded construction and handle reinforcement.": "Confirme si la estructura es cosida o unida por otro método, así como el refuerzo de las asas.",
  "Check artwork size, print method and colour references before sampling.": "Revise las dimensiones del diseño, el método de impresión y las referencias de color antes de preparar muestras.",
  "Are non-woven bags biodegradable?": "¿Son biodegradables las bolsas de tejido no tejido?",
  "Conventional PP non-woven fabric is a plastic material. Do not describe it as biodegradable or compostable without specific evidence. Confirm the actual material composition and local disposal options.": "El tejido no tejido convencional de PP es un material plástico. No debe describirse como biodegradable o compostable sin pruebas específicas. Confirme su composición real y las opciones locales de gestión de residuos.",
  "Custom foil insulated carry bags": "Bolsas térmicas con aluminio y asas a medida",
  "Foil insulated bags": "Bolsas térmicas con aluminio",
  "A foil-faced insulated carry format for food and grocery packaging. Specify the layer structure, finished dimensions and closure to match the intended delivery conditions.": "Formato de bolsa térmica con capa de aluminio y asas para alimentos y supermercados. Especifique las capas, las dimensiones finales y el cierre según las condiciones de entrega previstas.",
  "Foil-faced composite; layer specification to confirm": "Material compuesto con capa de aluminio; estructura por confirmar",
  "Food packaging · Grocery · Delivery": "Embalaje alimentario · Supermercados · Reparto",
  "Confirm the composition of every layer rather than relying on a silver appearance.": "Confirme la composición de cada capa, sin basarse únicamente en su aspecto plateado.",
  "Specify handle type, closure and the dimensions needed around your containers.": "Especifique el tipo de asa, el cierre y las dimensiones necesarias para sus recipientes.",
  "Request relevant contact-material documentation if direct food contact is intended.": "Si se prevé contacto directo con alimentos, solicite la documentación pertinente del material de contacto.",
  "Does a silver lining make a bag food-contact compliant?": "¿Un revestimiento plateado garantiza la conformidad para contacto alimentario?",
  "No. Appearance does not verify compliance. Review the actual contact layer, intended food type, temperature conditions and destination-market requirements with the supplier.": "No. El aspecto no demuestra la conformidad. Revise con el proveedor la capa real de contacto, el tipo de alimento, las condiciones de temperatura y los requisitos del mercado de destino.",
  "Custom EPE foam foil insulated bags": "Bolsas térmicas de espuma EPE con aluminio a medida",
  "EPE foam insulated bags": "Bolsas térmicas de espuma EPE",
  "Insulated packaging combining EPE foam and a foil-faced layer. Define the foam thickness, dimensions and seal construction for the protection and thermal requirements of your shipment.": "Embalaje térmico que combina espuma EPE y una capa de aluminio. Defina el espesor de la espuma, las dimensiones y el sellado según los requisitos de protección y temperatura de su envío.",
  "EPE foam with foil-faced layers": "Espuma EPE con capas de aluminio",
  "Fresh food · Cold-chain packing · Delivery": "Alimentos frescos · Cadena de frío · Reparto",
  "Specify foam thickness and density separately; they describe different properties.": "Especifique por separado el espesor y la densidad de la espuma: describen propiedades distintas.",
  "Review seam and closure construction alongside the insulating material.": "Revise las uniones y el cierre junto con el material aislante.",
  "Test the complete packed shipment, including any coolant and outer carton.": "Ensaye el envío completo, incluidos el refrigerante y la caja exterior.",
  "Is thicker foam always enough to improve delivery performance?": "¿Una espuma más gruesa basta para mejorar el resultado del reparto?",
  "Thickness is one factor. Contents, coolant quantity, closure, outer packaging, ambient temperature and transit time also matter. Validate the complete packing system under relevant conditions.": "El espesor es solo un factor. También influyen el contenido, la cantidad de refrigerante, el cierre, el embalaje exterior, la temperatura ambiente y el tiempo de transporte. Valide el sistema completo en condiciones representativas.",
  "Ice packs for insulated packaging": "Bolsas refrigerantes para embalaje térmico",
  "Ice packs": "Bolsas refrigerantes",
  "Coolant packs for use alongside insulated packaging. Select the pack format, fill specification and quantity for the actual product, route and required temperature range.": "Bolsas refrigerantes para utilizar junto con embalaje térmico. Seleccione el formato, el contenido y la cantidad según el producto, la ruta y el intervalo de temperatura requerido.",
  "Pack film and coolant formulation to confirm": "Película de la bolsa y formulación refrigerante por confirmar",
  "Cold-chain packing · Fresh food · Grocery": "Cadena de frío · Alimentos frescos · Supermercados",
  "Confirm pack dimensions, fill weight, seal integrity and handling instructions.": "Confirme las dimensiones, el peso de llenado, la integridad del sellado y las instrucciones de manipulación.",
  "Plan conditioning and placement to avoid unsuitable direct contact with temperature-sensitive contents.": "Planifique el acondicionamiento y la colocación para evitar un contacto directo inadecuado con productos sensibles a la temperatura.",
  "Verify performance through shipment testing; do not infer a temperature range from colour or appearance.": "Verifique el rendimiento mediante ensayos de transporte; no deduzca un intervalo de temperatura por el color o el aspecto.",
  "How many ice packs should be used per shipment?": "¿Cuántas bolsas refrigerantes se necesitan por envío?",
  "The answer depends on product mass, starting temperature, insulation, transit duration and external conditions. Establish the amount through testing of the complete packed shipment.": "La cantidad depende de la masa del producto, la temperatura inicial, el aislamiento, la duración del transporte y las condiciones externas. Determínela mediante ensayos del envío completo.",
  "Choose your format": "Elija el formato",
  "Select the product family and share your intended use.": "Seleccione la familia de productos y describa el uso previsto.",
  "Define the details": "Defina los detalles",
  "Confirm size, material, quantity, artwork and delivery requirements.": "Confirme las dimensiones, el material, la cantidad, el diseño y los requisitos de entrega.",
  "Review the sample": "Revise la muestra",
  "Review artwork and samples before approving final specifications.": "Revise el diseño y las muestras antes de aprobar las especificaciones finales.",
  "Plan production": "Planifique la producción",
  "Agree on the quotation, quality requirements and production schedule.": "Acuerde el presupuesto, los requisitos de calidad y el calendario de producción.",
  "Pack & dispatch": "Embalaje y expedición",
  "Confirm carton packing, inspection requirements and shipping terms.": "Confirme el embalaje en cajas, los requisitos de inspección y las condiciones de transporte.",
  "Complete & support": "Entrega y asistencia",
  "Check delivery details and coordinate any after-sales requirements.": "Compruebe los detalles de entrega y coordine las necesidades posventa.",
  "What does YUANEN manufacture?": "¿Qué fabrica YUANEN?",
  "YUANEN focuses on zipper insulated bags, hook-and-loop insulated bags, non-woven tote bags, foil insulated carry bags, EPE foam foil insulated bags and ice packs. Products can be discussed around the requirements of food, grocery and delivery packaging.": "YUANEN se especializa en bolsas térmicas con cremallera, bolsas con cierre de gancho y bucle, bolsas de tejido no tejido, bolsas térmicas con aluminio y asas, bolsas de espuma EPE con aluminio y bolsas refrigerantes. Las opciones se definen según las necesidades de embalaje de alimentos, supermercados y reparto.",
  "Where is the YUANEN factory network?": "¿Dónde se encuentran los centros de producción de YUANEN?",
  "YUANEN is based in Longgang, Wenzhou, with locations in Zhejiang, Shandong and Hunan. The company-confirmed areas are 20,000 m², 5,000 m² and 3,800 m² respectively, totalling 28,800 m².": "YUANEN tiene su sede en Longgang, Wenzhou, y centros en Zhejiang, Shandong y Hunan. Las superficies confirmadas por la empresa son de 20.000 m², 5.000 m² y 3.800 m², respectivamente, con un total de 28.800 m².",
  "What information is needed for a custom bag quote?": "¿Qué información se necesita para presupuestar bolsas a medida?",
  "Share the bag type, usable dimensions, layer structure, quantity, artwork, delivery destination and target date. Include testing, compliance and packing requirements so quotations cover the same scope.": "Indique el tipo de bolsa, las dimensiones útiles, la estructura de capas, la cantidad, el diseño, el destino y la fecha prevista. Incluya los requisitos de ensayo, conformidad y embalaje para que los presupuestos cubran el mismo alcance.",
  "What are the MOQ and lead time?": "¿Cuál es el pedido mínimo y el plazo de entrega?",
  "MOQ and lead time depend on the product, material, artwork and production schedule. Confirm both against your exact specification; the published capacity figure is not a delivery-time commitment for an individual order.": "El pedido mínimo y el plazo dependen del producto, el material, el diseño y la planificación de producción. Confírmelos según sus especificaciones exactas; la capacidad publicada no constituye un compromiso de entrega para un pedido concreto.",
  "How to specify an insulated bag": "Cómo definir las especificaciones de una bolsa térmica",
  "MATERIAL GUIDE": "GUÍA DE MATERIALES",
  "Compare outer fabrics, foil layers, EPE foam and closures as one complete packaging system.": "Compare tejidos exteriores, capas de aluminio, espuma EPE y cierres como un sistema completo de embalaje.",
  "Your custom bag order checklist": "Lista de requisitos para pedir bolsas a medida",
  "BUYING GUIDE": "GUÍA DE COMPRA",
  "From dimensions to sample approval, prepare the information behind a useful quote.": "Desde las dimensiones hasta la aprobación de muestras, prepare la información necesaria para un presupuesto útil.",
  "Wenzhou, Zhejiang": "Wenzhou, Zhejiang",
  "Shandong": "Shandong",
  "Hunan": "Hunan",
  "Insulated Bag Manufacturer & Custom Packaging | YUANEN": "Fabricante de bolsas térmicas y embalaje a medida | YUANEN",
  "YUANEN manufactures insulated bags, non-woven totes, foil packaging and ice packs. Explore custom options and our 28,800 m² factory network in China.": "YUANEN fabrica bolsas térmicas, bolsas de tejido no tejido, embalajes con aluminio y bolsas refrigerantes. Conozca nuestras opciones a medida y los 28.800 m² de instalaciones en China.",
  "Insulated Bags, Non-Woven Totes & Ice Packs | YUANEN": "Bolsas térmicas, no tejidas y refrigerantes | YUANEN",
  "Compare six insulated packaging and carry-bag families by material and use. Explore construction considerations, specification checklists and custom enquiries.": "Compare seis familias de embalajes térmicos y bolsas por material y uso. Consulte estructuras, listas de especificaciones y opciones de personalización.",
  "Food Delivery, Grocery & Cold-Chain Packaging | YUANEN": "Embalaje para reparto, supermercados y cadena de frío | YUANEN",
  "Choose packaging around real delivery conditions. Explore insulated bags for takeaway, non-woven retail packaging and cold-chain packing with ice packs.": "Elija embalajes según las condiciones reales de entrega. Explore bolsas térmicas para comida, bolsas de tejido no tejido para comercios y soluciones con refrigerantes para cadena de frío.",
  "Custom Bag Design & Order Process | YUANEN": "Diseño de bolsas a medida y proceso de pedido | YUANEN",
  "Plan your bag project from dimensions and materials to print artwork, samples and order requirements. Use a practical six-step specification process.": "Planifique su proyecto: dimensiones, materiales, diseño de impresión, muestras y requisitos del pedido. Siga un proceso práctico de seis pasos.",
  "YUANEN Factory | Insulated Packaging in China": "Fábrica YUANEN | Embalaje térmico en China",
  "Explore YUANEN production, material processing, sewing and storage. 10 years of packaging experience, three locations and company-reported daily capacity of 3 million+ pieces.": "Conozca la producción, el procesamiento de materiales, la confección y el almacenamiento de YUANEN. Diez años de experiencia, tres centros y una capacidad diaria declarada de más de 3 millones de unidades.",
  "Insulated Bag Materials & Buying Guides | YUANEN": "Materiales de bolsas térmicas y guías de compra | YUANEN",
  "Practical answers for packaging buyers: compare insulated bag materials, prepare a specification and review samples before ordering.": "Respuestas prácticas para compradores de embalajes: compare materiales, prepare especificaciones y revise muestras antes del pedido.",
  "Prepare a Custom Bag Enquiry | YUANEN": "Prepare su consulta de bolsas a medida | YUANEN",
  "Create a custom bag enquiry with your material, size, quantity and artwork requirements. Review and download your project brief.": "Prepare una consulta con sus requisitos de material, dimensiones, cantidad e impresión. Revise y descargue el documento de su proyecto.",
  "Privacy & Enquiry Data | YUANEN": "Privacidad y datos de consulta | YUANEN",
  "How the YUANEN website handles your enquiry brief, local downloads and optional email links.": "Cómo trata el sitio de YUANEN los documentos de consulta, las descargas locales y los enlaces opcionales de correo electrónico.",
  "Page not found | YUANEN": "Página no encontrada | YUANEN",
  "Find your way back to YUANEN packaging.": "Vuelva al sitio de embalajes YUANEN.",
  "YUANEN factory building": "Edificio de la fábrica YUANEN",
  "Insulated packaging production workshop": "Taller de producción de embalaje térmico",
  "Insulation material processing": "Procesamiento de materiales aislantes",
  "Bag assembly and sewing": "Confección y montaje de bolsas",
  "Insulation material rolls": "Bobinas de material aislante",
  "YUANEN office": "Oficinas de YUANEN",
  "Packed goods in storage": "Productos embalados en almacén",
  "Open menu": "Abrir menú",
  "Close menu": "Cerrar menú",
  "Language": "Idioma",
  "28,800": "28.800",
  "e.g. 3000": "p. ej., 3000",
  "e.g. 38 × 40 × 10": "p. ej., 38 × 40 × 10",
  "Custom bag enquiry — YUANEN": "Consulta de bolsas a medida — YUANEN"
}
