import { ArrowUpRight, Package, Layers3, Snowflake, Ruler, FileText, Clock3 } from 'lucide-react'
import { tx, type Bag, type Lang } from './data'
import { href } from './routes'
import FactoryPhoto from './FactoryPhoto'
import { imageUrl } from './product-media'
export default function ProductSections({bag,lang}:{bag:Bag;lang:Lang}){
 const t=(en:string,zh:string,es:string)=>tx(en,zh,es)[lang]
 const ice=bag.type==='ice', foil=bag.type==='foil'
 const sections=[
 ['applications',t('Applications','应用场景','Aplicaciones')],
 ['materials',t('Materials & construction','材料及工艺','Materiales y fabricación')],
 ['features',t('Product functions','产品功能','Funciones')],
 ['order-quantities',t('Order quantities','定制数量与分段','Cantidades')],
 ['pricing',t('MOQ & pricing','起订量与价格','Pedido mínimo y precio')],
 ['delivery',t('Lead time','交货时间','Plazos')],
 ['dimensions',t('Dimensions','产品尺寸','Medidas')],
 ['export',t('Export documentation','出口资料','Documentación de exportación')]]
 const heading=(i:number,icon:React.ReactNode)=><div className="detail-block-heading"><span>{String(i+1).padStart(2,'0')}</span><h2>{sections[i][1]}</h2>{icon}</div>
 const contact=`${href('/contact/',lang)}?bag=${bag.slug}`
 const detail=ice?(bag.slug==='water-fill-ice-packs'?'ice-pack-seal-detail':`${bag.slug}-main`):bag.slug==='self-adhesive-foil-bags'?'foil-adhesive-detail':foil?null:bag.slug==='square-zipper-cake-cooler'||bag.slug==='wide-base-meal-cooler'?'cooler-zipper-detail':'cooler-lining-detail'
 return <div className="product-specification">
 <nav className="detail-jump-nav" aria-label={t('Product details','产品详情导航','Detalles del producto')}>{sections.map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav>
 <section className="detail-block" id="applications">{heading(0,<Package size={24}/>)}<div className="detail-columns"><div><h3>{bag.use[lang]}</h3><p>{bag.intro[lang]}</p><p>{ice?t('Define the product mass, starting temperature, shipping route and insulated container before choosing the number and placement of packs.','选配冰袋前，明确产品重量、初始温度、运输路线和保温容器，再确认用量与摆放方式。','Defina masa, temperatura inicial, ruta y recipiente aislado antes de elegir cantidad y posición de los acumuladores.'):t('Start with your filled containers and delivery conditions. Review loading, closing and handling with a sample before confirming the packing format.','从装好后的餐盒或商品及实际配送条件出发，通过样品核对装入、封口与搬运过程。','Empiece por los recipientes llenos y las condiciones de reparto. Revise carga, cierre y manipulación con una muestra.')}</p></div><div className="application-check"><span className="eyebrow">{t('DEFINE YOUR PACK-OUT','明确实际包装方案','DEFINA SU EMBALAJE')}</span>{[t('Contents & filled weight','内装物与装载重量','Contenido y peso'),t('Route & ambient conditions','配送路线与环境条件','Ruta y condiciones ambientales'),t('Container & coolant fit','容器与冰源匹配','Ajuste de recipiente y refrigerante')].map(x=><p key={x}>{x}</p>)}</div></div></section>
 <section className="detail-block" id="materials">{heading(1,<Layers3 size={24}/>)}<div className="detail-columns"><div><h3>{bag.material[lang]}</h3><p>{ice?t('Agree the film structure, fill formulation, weight and sealing process. Review filled dimensions and seal integrity against the approved sample.','确认袋膜结构、蓄冷配方、填充重量及封口工艺，按确认样品核对填充后的尺寸与封口完整性。','Confirme película, formulación, peso de llenado y sellado. Revise medidas llenas e integridad del cierre con la muestra aprobada.'):foil?t('Confirm the foil-facing, insulating layer and bonding specification together. Edge sealing and gusset construction must match the selected format; agree thickness and dimensional tolerance before production.','一并确认铝箔面层、隔热层与复合规格。封边和折边结构应匹配所选袋型，投产前约定厚度与尺寸公差。','Confirme capa de aluminio, aislamiento y laminación. Sellado y fuelles deben corresponder al formato; acuerde espesor y tolerancias antes de producir.'):t('Specify the outer fabric, insulating layer, lining, handle attachment and closure as one construction. Review print area, edging and assembly details during sampling.','将外层面料、隔热层、内衬、提手固定及封口作为完整结构确认，打样时核对印刷区域、包边与组装细节。','Especifique tejido exterior, aislamiento, forro, fijación de asas y cierre como conjunto. Revise impresión, ribetes y montaje con la muestra.')}</p><ul className="detail-list">{bag.considerations.slice(0,2).map(x=><li key={x.en}>{x[lang]}</li>)}</ul></div>{detail?<figure className="construction-figure"><img src={imageUrl('packy/'+detail+'.webp')} alt={t('Illustrative construction detail','工艺细节效果示意','Detalle ilustrativo de construcción')} width="1024" height="1024" loading="lazy"/><figcaption>{t('AI construction illustration for this product family. Colour and details may differ; confirm the selected sample.','同系列工艺的 AI 效果示意，颜色与细节可能存在差异，请以所选款式样品确认。','Ilustración de construcción asistida por IA de esta familia. Color y detalles pueden variar; confirme la muestra.')}</figcaption></figure>:<figure className="construction-figure"><FactoryPhoto photo="converting" lang={lang}/><figcaption>{t('Material processing at the Longgang factory.','龙港工厂材料加工现场。','Procesamiento de materiales en la fábrica de Longgang.')}</figcaption></figure>}</div></section>
 <section className="detail-block" id="features">{heading(2,<Snowflake size={24}/>)}<div className="function-grid">{(ice?[
 [t('Coolant pairing','配套蓄冷','Refrigeración complementaria'),t('Use with an insulated package and an agreed conditioning method.','与保温包装配套，按约定方式预冷使用。','Utilice con embalaje aislado y preparación acordada.')],
 [t('Pack-out flexibility','灵活配置','Configuración adaptable'),t('Select pack size, fill weight, quantity and placement for the shipment.','按运输方案确认冰袋尺寸、重量、用量和位置。','Elija medidas, peso, cantidad y posición para el envío.')],
 [t('Seal review','封口检查','Revisión del sellado'),t('Check leakage and handling under the agreed test conditions.','按约定测试条件检查渗漏和搬运表现。','Compruebe fugas y manipulación en las condiciones acordadas.')]]:[
 [t('Insulation structure','隔热结构','Estructura aislante'),t('A specified composite construction helps limit heat exchange during handling.','通过约定复合结构，减少搬运配送中的热交换。','Una estructura compuesta especificada ayuda a limitar el intercambio térmico.')],
 [t('Practical packing','便捷装载','Embalaje práctico'),t('Match the opening and usable space to the actual product container.','按实际商品容器匹配开口及可用内部空间。','Adapte abertura y espacio útil al recipiente real.')],
 [t('Brand customization','品牌定制','Personalización de marca'),t('Agree dimensions, artwork and finishing against a sample.','结合样品确认尺寸、图稿和成品工艺。','Acuerde medidas, diseño y acabados mediante muestra.')]]).map(([title,body])=><div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div><p className="technical-note">{t('Temperature range and retention time depend on the complete loaded system and test conditions. No untested hour or temperature rating is claimed.','保温时长与温度范围取决于完整装载方案及测试条件，应以对应测试结果确认。','Temperatura y duración dependen del sistema cargado y de las condiciones de ensayo. Deben confirmarse mediante pruebas correspondientes.')}</p></section>
 <section className="detail-block" id="order-quantities">{heading(3,<Package size={24}/>)}<p>{t('Compare three order scenarios using the same approved specification. Quantity breaks are set in your written quotation for each size and artwork version.','按同一确认规格比较三类采购场景，具体数量分段按每个尺寸与印刷版本在正式报价单中确认。','Compare tres escenarios con la misma especificación aprobada. Los tramos se establecen por medida y diseño en la cotización escrita.')}</p><div className="quantity-grid">{[
 [t('Sample evaluation','样品评估','Evaluación de muestras'),t('Review material, dimensions, print and packing before placing a production order.','先核对材料、尺寸、印刷及装载效果，再确认生产订单。','Revise material, medidas, impresión y embalaje antes de pedir producción.')],
 [t('First production order','首批定制','Primer pedido'),t('Confirm the minimum quantity for the selected material, size and artwork.','按选定材质、尺寸及图稿确认最低定制数量。','Confirme el mínimo para material, medida y diseño elegidos.')],
 [t('Volume & repeat orders','批量及返单','Volumen y reposición'),t('Request quantity breaks, packing efficiency and staged delivery options.','核算数量阶梯、装箱效率与分批交付安排。','Solicite tramos de cantidad, eficiencia de embalaje y entregas parciales.')]].map(([title,body],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
 <section className="detail-block quote-block" id="pricing">{heading(4,<FileText size={24}/>)}<div className="detail-columns"><div><h3>{t('A quote built around your specification.','按您的具体规格报价。','Una cotización según su especificación.')}</h3><dl className="commercial-facts"><div><dt>{t('Minimum order','最低定制数量','Pedido mínimo')}</dt><dd>{t('Confirm by size, material and print version','按尺寸、材质与印刷版本确认','Confirmar por medida, material y diseño')}</dd></div><div><dt>{t('Unit price & currency','单价及币种','Precio unitario y moneda')}</dt><dd>{t('Written quotation required','以正式报价单为准','Según cotización escrita')}</dd></div><div><dt>{t('Quantity breaks','阶梯报价','Precios por volumen')}</dt><dd>{t('Based on your requested order quantities','按您提供的采购分段核算','Según cantidades solicitadas')}</dd></div></dl></div><div><p>{t('Send size, quantity, material, artwork and destination. Ask for sample/setup charges, packaging, freight, delivery terms and quotation validity to be listed separately.','提供尺寸、数量、材料、图稿和目的地，并在报价中分别确认打样制版费、包装、运费、贸易条款及报价有效期。','Envíe medidas, cantidad, material, diseño y destino. Solicite gastos de muestra, preparación, embalaje, transporte, condiciones y validez por separado.')}</p><a className="button primary" href={contact}>{t('Request product pricing','获取此款报价','Solicitar cotización')}<ArrowUpRight size={18}/></a></div></div></section>
 <section className="detail-block" id="delivery">{heading(5,<Clock3 size={24}/>)}<div className="delivery-steps">{[t('Specification & artwork approval','规格与图稿确认','Aprobación de especificación y diseño'),t('Sampling & sample approval','打样与样品确认','Muestreo y aprobación'),t('Production & inspection','生产与验货','Producción e inspección'),t('Dispatch & transit','出货与运输','Despacho y transporte')].map((v,i)=><div key={v}><span>{i+1}</span><strong>{v}</strong><p>{t('Schedule confirmed for your order','按订单确认时间','Plazo según pedido')}</p></div>)}</div><p>{t('Sampling, manufacturing and transit are separate periods. The confirmed quotation should state the starting conditions and planned dispatch date; destination arrival also depends on transport and customs.','打样、生产和运输分别核算。确认报价时应明确起算条件与计划出货日；到货时间另受运输及清关影响。','Muestreo, fabricación y transporte son plazos separados. La cotización debe indicar condiciones de inicio y despacho previsto; llegada depende también de transporte y aduanas.')}</p></section>
 <section className="detail-block" id="dimensions">{heading(6,<Ruler size={24}/>)}<div className="detail-columns"><div><h3>{t('Specify usable space, not just the outside size.','确认可用空间，不只看外尺寸。','Defina el espacio útil, además del exterior.')}</h3><p>{ice?t('Provide filled length, width, thickness and target fill weight. Confirm whether the quoted dimensions refer to the empty pouch or the filled pack.','提供填充后的长、宽、厚度及目标重量，明确报价尺寸指空袋还是填充后成品。','Indique largo, ancho, espesor y peso de llenado. Aclare si las medidas corresponden a la bolsa vacía o llena.'):t('Provide width × depth × height and mark internal or external dimensions. Allow space for coolant, the closure and loading clearance. For flat pouches, specify width, usable height and flap separately.','提供宽 × 深 × 高，并注明内尺寸或外尺寸。为冰源、封口及装载预留空间；平口袋应分别说明袋宽、可用高度和封口翻边。','Indique ancho × fondo × alto y medidas internas o externas. Reserve espacio para refrigerante y cierre. En sobres planos, especifique ancho, altura útil y solapa por separado.')}</p><p className="technical-note">{t('Custom dimensions and tolerances are confirmed during sampling. Supply mm or inches consistently (1 in = 25.4 mm).','定制尺寸与公差在打样时确认。可使用毫米或英寸，并保持单位一致（1 英寸 = 25.4 毫米）。','Medidas y tolerancias se confirman con muestras. Use mm o pulgadas de forma consistente (1 pulgada = 25,4 mm).')}</p></div><div className="dimension-guide"><span>W × D × H</span><p>{t('Width × Depth × Height','宽 × 深 × 高','Ancho × Fondo × Alto')}</p><div>{t('Internal / External · mm / in','内尺寸 / 外尺寸 · mm / in','Interior / Exterior · mm / in')}</div><small>{t('Dimension notation; not a stock-size specification.','尺寸标注方式，非现货规格。','Notación de medidas; no es una medida de inventario.')}</small></div></div></section>
 <section className="detail-block" id="export">{heading(7,<FileText size={24}/>)}<p>{t('Agree the documentation required by the destination and the exact product construction before ordering. These are document categories to review, not a claim that a certificate has been issued.','下单前按目的地与具体产品结构确认所需文件。以下展示出口资料核对范围，不代表已取得相应认证。','Acuerde documentos según destino y construcción antes de pedir. Estas son categorías para revisar, no una afirmación de certificación.')}</p><div className="export-documents">{[
 [t('Commercial invoice & packing list','商业发票与装箱单','Factura comercial y lista de empaque'),t('Order quantities, packing, weights and shipping terms','订单数量、装箱、重量及交货条款','Cantidades, embalaje, pesos y condiciones')],
 [t('Material & product specification','材质与产品规格资料','Especificación de material y producto'),t('Layer composition, dimensions and approved sample reference','复合层成分、尺寸与确认样品编号','Composición, medidas y referencia de muestra')],
 [t('Applicable test documentation','适用检测资料','Documentación de ensayos aplicable'),t('Match the report scope to the material, intended use and destination','按材料、用途与目的地核对报告范围','Verificar alcance según material, uso y destino')],
 [t('Coolant information, where applicable','冰源资料（适用时）','Información del refrigerante, si corresponde'),t('Composition, handling and relevant safety documentation','成分、操作说明及相关安全文件','Composición, manipulación y documentación de seguridad')]].map(([title,body])=><div key={title}><FileText size={24}/><h3>{title}</h3><p>{body}</p><span>{t('Confirm for your order','按订单核对提供','Confirmar para su pedido')}</span></div>)}</div><a className="text-link" href={contact}>{t('Discuss your export requirements','沟通出口资料要求','Consultar requisitos de exportación')}<ArrowUpRight size={17}/></a></section>
 </div>
}
