import {useRef,useState} from 'react'
import {ArrowUpRight,FileText,Expand, X} from 'lucide-react'
import {brand,tx,type Lang} from './data'
import {href} from './routes'
import {documentCategories,qualityDocuments,qualityImage,type QualityDocument} from './documentation-data'

export function DocumentationLink({lang}:{lang:Lang}) {
 const t=(en:string,zh:string,es:string)=>tx(en,zh,es)[lang]
 return <div className="documentation-link"><FileText size={29} strokeWidth={1.4}/><div><span className="eyebrow">{t('QUALITY & DOCUMENTATION','质量与资料','CALIDAD Y DOCUMENTACIÓN')}</span><h3>{t('Review the records behind the specification.','按具体范围，查阅审核与检测资料。','Consulte los documentos de la especificación.')}</h3><p>{t('Explore affiliated-factory audits and material sample reports, with the named holder and scope. Confirm the match to your cold-chain order.','查看关联工厂审核与材料样品报告，了解文件主体和适用范围，并核对与冷链订单的对应关系。','Consulte auditorías de fábricas vinculadas e informes de muestras, con titular y alcance. Confirme su correspondencia con el pedido térmico.')}</p></div><a className="text-link" href={href('/quality/',lang)}>{t('View documents','查看资料','Ver documentos')}<ArrowUpRight size={18}/></a></div>
}

export default function Quality({lang}:{lang:Lang}) {
 const t=(en:string,zh:string,es:string)=>tx(en,zh,es)[lang]
 const [filter,setFilter]=useState('all')
 const [selected,setSelected]=useState<QualityDocument|null>(null)
 const dialog=useRef<HTMLDialogElement>(null)
 const lastTrigger=useRef<HTMLButtonElement|null>(null)
 const visible=qualityDocuments.filter(d=>filter==='all'||d.category===filter)
 const request=(d:QualityDocument)=>`mailto:${brand.email}?subject=${encodeURIComponent(`YUANEN document request - ${d.number}`)}&body=${encodeURIComponent(t(`Please provide the complete record ${d.number} and confirm its applicability to my order.\nProduct / material:\nDestination:\nRequired tests:`,`请提供 ${d.number} 完整资料，并确认与本订单的适用关系。\n产品／材料：\n目的地：\n需要的检测：`,`Solicito el documento completo ${d.number} y confirmación de su aplicabilidad a mi pedido.\nProducto / material:\nDestino:\nEnsayos necesarios:`))}`
 return <>
  <section className="quality-hero"><div className="container"><nav className="breadcrumbs" aria-label={t('Breadcrumb','面包屑导航','Ruta de navegación')}><a href={href('/',lang)}>{t('Home','首页','Inicio')}</a><span>/</span><span aria-current="page">{t('Quality & documentation','质量与资料','Calidad y documentación')}</span></nav><div className="quality-intro"><div><span className="eyebrow">{t('FACTORY / MATERIAL / SAMPLE','工厂 / 材料 / 样品','FÁBRICA / MATERIAL / MUESTRA')}</span><h1>{t('Factory Audits &\nMaterial Test Reports','工厂审核与\n材料检测资料','Auditorías de fábrica e\ninformes de materiales')}</h1></div><div><p>{t('Factory audits. Material certificates. Sample test reports.','工厂审核、面料认证与样品检测报告。','Auditorías de fábrica, certificados de tejido e informes de ensayo.')}</p><p>{t('Records from our affiliated facilities, presented with their original holders, dates and specific scope. Review the relevant document for your purchasing requirements.','汇集关联工厂资料，保留原文件主体、日期及具体范围，为采购要求提供清晰的核对依据。','Documentos de nuestras instalaciones vinculadas, con titulares originales, fechas y alcance. Revise el documento pertinente a su compra.')}</p></div></div><div className="quality-types">{Object.entries(documentCategories).map(([id,label],i)=><div key={id}><span>0{i+1}</span><strong>{label[lang]}</strong></div>)}</div></div></section>
  <section className="container quality-library"><div className="quality-library-heading"><div><span className="eyebrow">{t('DOCUMENT LIBRARY','资料目录','BIBLIOTECA DOCUMENTAL')}</span><h2>{t('Find the relevant record.','按资料类型查阅。','Encuentre el documento pertinente.')}</h2></div><p>{t('Match the named factory, material and tested sample to the product you order. These records are not blanket certification of YUANEN’s insulated bags or ice packs.','请按实际订单核对工厂、材料与送检样品。这些资料不代表远恩全部保温袋或冰袋成品均已获得认证。','Verifique fábrica, material y muestra con el producto pedido. Estos documentos no certifican de forma general todas las bolsas térmicas o acumuladores de YUANEN.')}</p></div>
   <div className="quality-filters" role="group" aria-label={t('Document type','资料类型','Tipo de documento')}>{[['all',t('All records','全部资料','Todos')],...Object.entries(documentCategories).map(([id,label])=>[id,label[lang]])].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}<span>{id==='all'?qualityDocuments.length:qualityDocuments.filter(d=>d.category===id).length}</span></button>)}</div><p className="quality-count" aria-live="polite">{t(`${visible.length} records`,`${visible.length} 份资料`,`${visible.length} documentos`)}</p>
   <div className="quality-records">{visible.map(d=><article className="quality-record" id={d.id} key={d.id}><div className="quality-document-preview"><button onClick={event=>{lastTrigger.current=event.currentTarget;setSelected(d);dialog.current?.showModal()}} aria-label={t(`Preview ${d.number}`,`预览 ${d.number}`,`Vista previa ${d.number}`)}><img src={qualityImage(d.image)} alt={t(`${d.title.en}, original first page`,`${d.title.zh}，原文件首页`,`${d.title.es}, primera página original`)} width="900" height="1273" loading="lazy"/><span><Expand size={15}/>{t('Enlarge cover','放大首页','Ampliar portada')}</span></button><p>{t(`First page of ${d.pages} · Summary below`,`${d.pages} 页原件的首页 · 下方为范围摘要`,`Primera página de ${d.pages} · Resumen del alcance`)}</p></div><div className="quality-document-copy"><span className="eyebrow">{documentCategories[d.category][lang]}</span><h3>{d.title[lang]}</h3><dl><div><dt>{t('Document no.','文件编号','Número')}</dt><dd>{d.number}</dd></div><div><dt>{t('Named entity','文件主体','Entidad indicada')}</dt><dd>{d.holder}</dd></div><div><dt>{t('Organization','机构','Organización')}</dt><dd>{d.issuer}</dd></div><div><dt>{d.category==='audit'?t('Audit date','审核日期','Fecha de auditoría'):t('Issue date','签发日期','Fecha de emisión')}</dt><dd>{d.date}</dd></div>{d.validUntil&&<div><dt>{t('Valid until stated','文件有效期至','Vigencia indicada')}</dt><dd>{d.validUntil}</dd></div>}<div><dt>{t('Recorded result','文件结论','Resultado registrado')}</dt><dd>{d.result[lang]}</dd></div></dl><div className="quality-scope"><h4>{t('Scope of the record','资料适用范围','Alcance del documento')}</h4><p>{d.scope[lang]}</p><p className="quality-scope-note">{d.note[lang]}</p></div><a className="text-link" href={request(d)}>{t('Request full record','索取完整资料','Solicitar documento completo')}<ArrowUpRight size={17}/></a></div></article>)}</div>
   <div className="quality-order-note"><span className="eyebrow">{t('FOR YOUR ORDER','针对您的订单','PARA SU PEDIDO')}</span><h2>{t('Confirm product-specific requirements.','核对您这款产品所需的资料。','Confirme los requisitos de su producto.')}</h2><p>{t('Send the product, material, destination market and required tests. We can review the document scope and discuss any additional testing needed for the selected construction. Report availability does not establish food-contact compliance or a thermal rating.','提供产品、材料、目标市场与检测要求，以便核对已有资料的范围，并沟通所选结构需要补充的检测。已有报告不等同于食品接触合规证明或保温性能评级。','Indique producto, material, mercado de destino y ensayos requeridos. Revisaremos el alcance y los ensayos adicionales necesarios para la construcción elegida. Disponer de informes no acredita aptitud alimentaria ni una clasificación térmica.')}</p><a className="button primary" href={href('/contact/',lang)}>{t('Discuss documentation','沟通资料要求','Consultar documentación')}<ArrowUpRight size={18}/></a></div>
  </section>
  <dialog ref={dialog} className="quality-preview-dialog" aria-label={t('Original document cover','原文件首页','Portada original del documento')} onClose={()=>{setSelected(null);lastTrigger.current?.focus()}}><button className="icon-button quality-close" onClick={()=>dialog.current?.close()} aria-label={t('Close preview','关闭预览','Cerrar vista previa')}><X/></button>{selected&&<><p>{selected.number} · {t('Original first page','原文件首页','Primera página original')}</p><img src={qualityImage(selected.image)} alt={selected.title[lang]}/></>}</dialog>
 </>
}
