import { productDescriptions } from './seo-descriptions'
import { collections } from './collections'
import { bags, guides, tx, type Lang, type Text } from './data'
export type Page = { path: string; type: string; title: Text; description: Text; slug?: string }
export const pages: Page[] = [
  {path:'/quality/',type:'quality',title:tx('Factory Audits & Material Test Reports | YUANEN','关联工厂审核与材料检测资料 | 远恩','Auditorías de fábrica e informes de materiales | YUANEN'),description:tx('Review affiliated-factory BSCI audit records, CTT sample test reports and an OEKO-TEX fabric certificate, with named holders, dates and scope.','查阅关联工厂的 BSCI 审核、CTT 样品检测报告及 OEKO-TEX 面料证书，核对文件主体、日期与适用范围。','Consulte auditorías BSCI de fábricas vinculadas, informes CTT de muestras y un certificado OEKO-TEX de tejido, con titulares, fechas y alcance.')},
  {path:'/',type:'home',title:tx('Insulated & Cold Chain Packaging Manufacturer | YUANEN','远恩 | 保温冷链包装生产厂家','Fabricante de embalaje térmico y cadena de frío | YUANEN'),description:tx('Custom insulated foil bags, cooler bags and ice packs for food delivery and cold-chain packing. Explore products, manufacturing and custom order specifications.','专注铝箔保温袋、保温包和配套冰袋，服务餐饮配送与冷链包装，了解产品、生产工艺和定制采购规格。','Bolsas térmicas, bolsas de aluminio y acumuladores de frío para reparto alimentario. Explore productos, fabricación y especificaciones a medida.')},
  {path:'/products/',type:'catalog',title:tx('Insulated Bags & Cold Chain Products | YUANEN','保温袋与冷链产品中心 | 远恩','Bolsas térmicas y productos de cadena de frío | YUANEN'),description:tx('Explore insulated packaging: lunch cooler bags, bakery cake carriers, foil pouches, insulated delivery totes and ice packs. Review real sample photos and specifications.','探索保温冷链产品：午餐保温包、烘焙蛋糕保温包、铝箔袋、保温外卖袋及冰袋，查看实拍样品与定制规格。','Explore bolsas térmicas de almuerzo y pastelería, bolsas de aluminio y reparto, y acumuladores de frío. Consulte fotos de muestras y especificaciones.')},
  {path:'/applications/',type:'applications',title:tx('Food Delivery, Grocery & Cold-Chain Packaging | YUANEN','餐饮配送、商超与冷链包装应用 | 远恩'),description:tx('Match insulated bags and ice packs to takeaway meals, grocery carrying and fresh-food shipping. Compare loading, closures, coolant space and route testing.','按外卖餐盒、商超手提及生鲜运输需求选择保温袋与冰袋，比较装载、封口、冰源空间和路线测试要求。','Elija bolsas térmicas y refrigerantes para comidas, compras y alimentos frescos. Compare carga, cierres, espacio y ensayos de ruta.')},
  ...collections.map(c=>({path:`/collections/${c.slug}/`,type:'collection',slug:c.slug,title:c.title,description:c.description})),
  ...bags.map(b=>({path:`/products/${b.slug}/`,type:'bag',title:b.seoTitle||tx(`${b.name.en}: Materials & Specifications | YUANEN`,`${b.name.zh}：材质与规格 | 远恩`,`${b.name.es}: materiales y especificaciones | YUANEN`),description:productDescriptions[b.slug]||b.intro,slug:b.slug})),
  {path:'/customization/',type:'custom',title:tx('Custom Insulated Bags: Sampling & Bulk Orders | YUANEN','保温袋定制・打样与批量订购流程 | 远恩','Bolsas térmicas a medida: muestras y pedidos | YUANEN'),description:tx('Plan custom insulated bags from dimensions and EPE layers to logo artwork, sample approval and bulk production. Confirm order quantity and delivery requirements.','从尺寸、EPE 结构、品牌图稿到样品确认与批量生产，规划保温袋定制项目，并核对采购数量与交货要求。','Planifique bolsas térmicas: medidas, capas EPE, logotipo, aprobación de muestra y producción. Confirme cantidad y condiciones de entrega.')},
  {path:'/about/',type:'about',title:tx('YUANEN Factory | Insulated Packaging in China','远恩工厂 | 三地保温包装生产布局'),description:tx('Explore YUANEN production, material processing, sewing and storage. 10 years of packaging experience, three locations and company-reported daily capacity of 3 million+ pieces.','了解远恩的生产、材料加工、缝制和仓储。10 年包装经验，温州、山东、湖南三地布局，日产能 300 万+。')},
  {path:'/guides/',type:'guides',title:tx('Insulated Packaging Materials & Buying Guides | YUANEN','保温冷链包装材质与采购指南 | 远恩','Materiales y guías de compra de embalaje térmico | YUANEN'),description:tx('Compare foil bags, fabric coolers, box liners and ice packs. Specify insulation materials and prepare MOQ, sampling and quotation questions before ordering.','比较铝箔袋、面料保温包、箱内衬和冰袋，确认隔热材料，准备起订量、打样与报价问题后再下单。','Compare bolsas de aluminio y tejido, revestimientos y refrigerantes. Especifique materiales y prepare preguntas de mínimos, muestras y cotización.')},
  ...guides.map(g=>({path:`/guides/${g.slug}/`,type:'guide',title:tx(`${g.title.en} | YUANEN`,`${g.title.zh} | 远恩`,`${g.title.es} | YUANEN`),description:g.summary,slug:g.slug})),
  {path:'/contact/',type:'contact',title:tx('Request a Custom Insulated Packaging Quote | YUANEN','保温冷链包装定制询价 | 远恩','Solicitar cotización de embalaje térmico | YUANEN'),description:tx('Prepare a quote request for insulated bags, foil liners or ice packs with size, quantity, artwork and destination. Download your brief or contact YUANEN.','填写保温袋、铝箔内衬或冰袋的尺寸、数量、图稿及目的地，整理和下载询价需求，联系远恩获取报价。','Prepare su consulta de bolsas térmicas, revestimientos o refrigerantes con medidas, cantidad, diseño y destino. Descargue el resumen o contacte con YUANEN.')},
  {path:'/privacy/',type:'privacy',title:tx('Privacy & Enquiry Data | YUANEN','隐私与询价数据说明 | 远恩'),description:tx('How the YUANEN website handles your enquiry brief, local downloads and optional email links.','了解远恩网站如何处理询价需求、本地下载及可选的邮件链接。')},
]
export const base = import.meta.env.BASE_URL.replace(/\/$/,'')
export const href = (path:string,lang:Lang) => `${base}${lang==='en'?'':`/${lang}`}${path}`
export function resolveRoute(path:string) {
  let clean = decodeURI(path.split('?')[0])
  if (base && clean.startsWith(`${base}/`)) clean = clean.slice(base.length)
  const lang:Lang = /^\/zh(?:\/|$)/.test(clean)?'zh':/^\/es(?:\/|$)/.test(clean)?'es':'en'
  if(lang!=='en') clean = clean.slice(lang.length+1) || '/'
  if(!clean.endsWith('/')) clean += '/'
  const page = pages.find(p=>p.path===clean)
  return {lang, page:page || {path:'/404/',type:'404',title:tx('Page not found | YUANEN','页面不存在 | 远恩'),description:tx('Find your way back to YUANEN packaging.','返回远恩包装网站。')}}
}
