import { tx, type Text } from './data'
// Editorial summaries: one distinct product/intent per existing URL. No search-volume claims.
export const productDescriptions:Record<string,Text> = {
 'gusseted-self-seal-foil-bags':tx('Gusseted foil insulated pouches with an adhesive flap for boxed food. Review sample photos, base depth and closure fit before a bulk quotation.','带底部空间与自粘翻盖的立体铝箔保温袋，用于盒装食品。查看实拍样品，核对底深、开口与封口贴合后获取批量报价。','Bolsas térmicas de aluminio con base y solapa adhesiva para alimentos en caja. Revise fotos, profundidad y cierre antes de cotizar.'),
 'foil-insulated-box-liners':tx('Foil insulated liners for shipping boxes. Review actual liner placement, usable box dimensions, top closure and coolant space for cold-chain packing.','冷链运输箱用铝箔保温内衬，查看箱内装载实拍，确认箱体可用内尺寸、顶部封口和冰源空间，外箱另行确认。','Revestimientos térmicos de aluminio para cajas de envío. Revise colocación, medidas interiores, cierre superior y espacio para refrigerantes.'),
 'side-absorbing-ice-packs':tx('Side-absorbing ice packs for insulated shipping boxes. Compare sample sizes, water-entry edges, filled dimensions and preparation before ordering.','保温运输箱配套双侧吸自吸水冰袋，比较实拍尺寸、吸水边缘、填充后轮廓及准备要求，按具体样品确认订单规格。','Acumuladores de absorción lateral para cajas térmicas. Compare tamaños de muestra, bordes de entrada, medidas llenas y preparación.'),
 'double-film-self-absorbing-ice-packs':tx('Double-film self-absorbing ice packs for food shipping. View front and reverse sample photos; confirm absorption, seals and filled size for your pack-out.','食品冷链配套双面膜自吸水冰袋，查看正反面实拍，确认吸水过程、封口及填充后尺寸，配合实际包装试装。','Acumuladores autoabsorbentes de doble cara para alimentos. Vea fotos de ambas caras y confirme absorción, sellos y tamaño lleno.'),
 'compact-insulated-lunch-bags':tx('Custom lunch cooler bags with handles, a flat base and zip lid. View real samples and compare lunch-box fit, colours and logo requirements for bulk orders.','小型手提午餐保温包，平底搭配拉链盖。查看实拍样品，按餐盒尺寸确认装载空间、颜色和品牌印刷，咨询批量定制。','Bolsas térmicas de almuerzo con asas, base plana y tapa con cremallera. Vea muestras y confirme ajuste, colores y logotipo para pedidos.'),
 'gold-trim-insulated-cake-bags':tx('White and gold cake cooler bags with zip lids for bakery gift boxes. View real loading photos and compare box clearance, heights and custom branding.','白金色拉链蛋糕保温包，适配烘焙礼盒。查看装盒实拍与高矮款式，核对盒体余量、开口及品牌定制要求。','Bolsas térmicas blancas y doradas para tartas, con cremallera. Vea fotos de carga y compare alturas, espacio para caja y personalización.'),
 'self-adhesive-foil-bags':tx('Peel-and-seal foil insulated bags for takeaway and fresh-food containers. Compare opening width, EPE layers, stock-size printing and custom order terms.','餐饮外卖与生鲜容器用自粘铝箔保温袋，核对可用开口、EPE 复合结构，查看现货尺寸印刷与定制订购条件。','Bolsas térmicas autoadhesivas para comida y alimentos frescos. Compare abertura, capas EPE, impresión en medidas existentes y pedidos a medida.'),
 'open-top-foil-bags':tx('Open-top foil and foam bags for seafood, barbecue and takeaway trays. Review sample photos, usable clearance and a separately agreed closure method.','海鲜、烧烤与外卖餐盘用平口铝箔保温袋，查看实拍和可用空间，按打包流程另行确认封口方式与采购规格。','Bolsas térmicas abiertas para marisco, barbacoa y bandejas de comida. Revise fotos, espacio útil y un método de cierre acordado aparte.'),
 'hand-finished-gusseted-foil-bags':tx('Hand-finished gusseted foil insulated bags for meal boxes. Compare formed bases, joining details and loaded fit; review available sizes and order terms.','盒餐用手工立体铝箔保温袋，比较成型底部、连接细节与装载匹配，查看可选尺寸和定制采购条件。','Bolsas térmicas de aluminio con base de acabado manual para comidas en caja. Compare base, uniones, ajuste cargado y condiciones de pedido.'),
 'machine-formed-gusseted-foil-bags':tx('Machine-formed gusseted foil bags for grocery packing. Confirm base profile, seal positions, usable dimensions and printing for repeat bulk orders.','商超包装用机器立体铝箔袋，核对底型、封边位置、可用尺寸与印刷方案，为重复批量采购准备统一规格。','Bolsas térmicas con base formada a máquina para compras. Confirme perfil, sellos, medidas útiles e impresión para pedidos recurrentes.'),
 'gusseted-foil-cake-bags':tx('Gusseted foil insulated cake bags for bakery boxes. Check cake-board footprint, box height and top closure clearance before selecting sizes and printing.','烘焙蛋糕盒用立体铝箔保温袋，按蛋糕底板、盒体高度与顶部封口余量确认尺寸，并咨询印刷与订购条件。','Bolsas térmicas de aluminio con base para tartas. Revise huella de la base, altura de caja y espacio de cierre antes de elegir medidas e impresión.'),
 'water-fill-ice-packs':tx('Water-fill ice packs for insulated food shipping. Review sample photos, available sizes, fill and freeze requirements, printing MOQ and production lead time.','食品保温运输用注水冰袋，查看实拍、现有规格、注水冷冻要求，以及印刷起订量和生产交期，按完整包装测试用量。','Acumuladores rellenables para envío de alimentos. Vea fotos, medidas, llenado, congelación, mínimos de impresión y plazo de producción.'),
 'self-absorbing-ice-packs':tx('Self-absorbing ice packs for seafood and cold-chain packing. Review soaking, draining, expanded size, stock specifications and custom printing requirements.','海鲜与冷链包装用自吸水冰袋，核对吸水、沥水、膨胀后尺寸，查看现有规格和定制印刷要求。','Acumuladores autoabsorbentes para marisco y cadena de frío. Revise absorción, escurrido, tamaño expandido, medidas e impresión personalizada.'),
 'segmented-ice-sheets':tx('Flexible segmented ice sheets for cold-chain packing. Compare cell layout, approved cutting lines, placement and available specifications before ordering.','冷链包装用柔性分格冰片，比较格子布局、允许裁切线与摆放方式，核对现有规格、印刷及采购条件。','Láminas de frío flexibles y segmentadas. Compare celdas, líneas de corte autorizadas, colocación y especificaciones antes de pedir.'),
 'self-seal-non-woven-delivery-bags':tx('Custom non-woven insulated takeaway bags with self-seal strips and handles. Compare stock-size printing, fully custom quantities, samples and lead times.','带自封胶条与提手的无纺布保温外卖袋，适配餐饮和饮品，比较现货尺寸印刷、全定制数量、打样与交期。','Bolsas térmicas de tejido no tejido con cierre adhesivo y asas. Compare impresión en medidas existentes, cantidades, muestras y plazos.'),
 'square-zipper-cake-cooler':tx('Box-shaped insulated cake delivery bags with a zipper and broad base. View mint-green sample photos and check cake-box clearance, lining and handles.','方形宽底拉链蛋糕配送保温包，查看薄荷绿样品实拍，核对蛋糕盒装载余量、内衬、提手及定制要求。','Bolsas térmicas cuadradas para tartas con cremallera y base ancha. Vea la muestra menta y revise espacio para caja, forro y asas.'),
 'upright-dessert-cooler':tx('Upright cooler tote bags for desserts and drinks. Review the tall profile, handle drop, opening and print placement for a custom bakery packaging order.','甜品与饮品用直立手提保温包，按烘焙包装需求确认袋身高度、提手垂距、开口和印刷位置，咨询定制采购。','Bolsas térmicas verticales para postres y bebidas. Revise altura, caída de asas, abertura e impresión para embalaje de pastelería a medida.'),
 'wide-base-meal-cooler':tx('Wide-base insulated meal delivery bags with zipper openings. Plan horizontal container layout, base support and balanced handles before a custom bulk order.','宽底拉链餐饮配送保温包，按实际餐盒规划横向排列、底部支撑与提手平衡，确认样品后咨询批量定制。','Bolsas térmicas de base ancha con cremallera para reparto de comidas. Planifique envases, soporte y equilibrio de asas antes del pedido.'),
 'upright-grocery-cooler':tx('Custom insulated grocery bags with zippers and carry handles. Compare upright loading, coolant space and logo printing for fresh-food and seafood packing.','带拉链和手提的商超保温袋定制，按生鲜与海鲜包装确认直立装载、冰源空间及品牌印刷，核对样品后批量采购。','Bolsas térmicas para compras con cremallera y asas. Compare carga vertical, refrigerantes y logotipo para alimentos frescos y marisco.'),
}
